### ISSUE TITLE
new term: aspirate from proximal femur

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ontology#1]
For new term requests, please provide the following information:

I'm not sure if attaching aspirate is useful for the ontology or if this should be done in a different way e.g. bone marrow from ...

I have requested more information from the scientist to find a more specific location to check that 'proximal' is an adequate anatomical description.

For now I am just using the UBERON term for femur UBERON:0000981

## Preferred term label

aspirate from proximal femur or proximal femur 

## Synonyms

not known

## Textual definition

This is a bone marrow sample extracted by aspiration from the proximal femur.

## Suggested parent term

not sure

**Comment by daniwelter** [comment]
We already have bone marrow aspiration in EFO - use this term in conjunction with an appropriate sampling location
