### ISSUE TITLE
[ITR] - Differential gene expression analysis results

### ISSUE THREAD

**Issue by idazucchi** [HumanCellAtlas/ontology#101]
Hi @paolaroncaglia!

After some discussion we have decided to include the results of differential gene expression analysis in the DCP, but at the moment we don’t have in the HCAO a term that can accurately describe these files.

I’ve found a term that describes the results of dge analysis and I’ve tentatively filled in the ticket, but I’m not sure it can be imported in our ontology.
If you have any suggestions we would be very happy to hear them!

## Source ontology identifier

OBI:0002584

## Destination ontology

HCAO

## Preferred term label

differential expression analysis data

## Textual definition

The results of a differential expression analysis.

## Suggested parent term

Data data:0006

## Use case

Correctly identify files that are the results of differential gene expression analysis

## Attribution

https://orcid.org/0000-0002-4900-7575

**Comment by paolaroncaglia** [comment]
Hi @idazucchi ,

We can import OBI:0002584 'differential expression analysis data' into EFO (as a child of EFO IAO:0000100 'data set'), in time for the EFO release (March 15th).
The OBI term would then be placed in the 'information entity' branch and would be available to you at the next HCAO build + release (March 16th + ~2 days needed for deployment). 
I'll comment back here when it's done. Thanks.

Paola

**Comment by idazucchi** [comment]
Thank you Paola! This is great news, we should be able to use the term for datasets within this release then

**Comment by paolaroncaglia** [comment]
@idazucchi 
OBI:0002584 'differential expression analysis data' is now in EFO (as a child of EFO IAO:0000100 'data set').
It will be available to HCA after the EFO and HCAO releases next week, as soon as the updated OLS instance is deployed after March 16th. I'll close this ticket now, but feel free to ping me if there's any issue. Thanks.
