### ISSUE TITLE
[NTR] Liver abscess

### ISSUE THREAD

**Issue by ipediez** [HumanCellAtlas/ontology#103]
## Preferred term label

Liver abscess

## Synonyms

Hepatic abscess

## Textual definition

An abscess in the liver

## Suggested parent term

[Abscess (MONDO:0005227)](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005227)

## Use case

This pathology is listed as one of the pathologies of a human donor for a liver single-cell project

## Attribution

0000-0002-2658-1136

**Comment by ipediez** [comment]
I would need a new term also for Intersphincteric abscess. That would be for the same use case and would fall under the same parent term and have a similar description. I haven't created the ticket yet, in case you want to discuss here if there are already terms available or that we can import. Both terms would have similar ones available on SNOMEDCT: [Abscess of liver (27916005)](https://www.ebi.ac.uk/ols/ontologies/snomed/terms?iri=http%3A%2F%2Fsnomed.info%2Fid%2F27916005) and [Intersphincteric abscess (235795007)](https://www.ebi.ac.uk/ols/ontologies/snomed/terms?iri=http%3A%2F%2Fsnomed.info%2Fid%2F235795007). Do you want me to create a new ticket for Intersphincteric abscess?

**Comment by paolaroncaglia** [comment]
@ipediez no need to open a separate ticket, thanks. I'll look into both terms today.

**Comment by paolaroncaglia** [comment]
@ipediez I double-checked Mondo (including potential synonyms of your requested terms) and I confirm that there are no specific terms currently available. (EFO imports 'Liver abscess' from the Human Phenotype Ontology, so as a phenotype term that's not available in HCAO.)
- [ ] I will ask Mondo to create 'liver abscess' and 'intersphincteric abscess'
- [ ] I'll comment back here when they are available to you (at the earliest, with the HCAO release scheduled for April 20th)

In the meantime, if you need to annotate for a release before that date, you could use [Abscess (MONDO:0005227)](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005227) and combine that with the anatomy terms UBERON:0002107 'liver' and UBERON:0004916 'anal sphincter', respectively.

**Comment by paolaroncaglia** [comment]
@ipediez 
The 2 new disease terms you requested have been created in Mondo, but not released yet. As anticipated, they will be public with the next Mondo release, and available to HCA wranglers after May 17th. Here are the IDs for future reference:
MONDO:0700051 liver abscess (disease)
MONDO:0700052 intersphincteric abscess

**Comment by dosumis** [comment]
Pending.

**Comment by paolaroncaglia** [comment]
@ipediez 
MONDO:0700051 liver abscess (disease)
and
MONDO:0700052 intersphincteric abscess
will be available in HCAO as soon as the new release is in the OLS instance, pending https://github.com/ebi-ait/hca-ebi-dev-team/issues/487. Thank you.
