### ISSUE TITLE
[ENQ] Review Uberon terms included in past HCA submissions

### ISSUE THREAD

**Issue by paolaroncaglia** [HumanCellAtlas/ontology#104]
@ESapenaVentura @dosumis and @zoependlington 
Hi, as per Slack comm with @pnejad ,

Q: "Enrique expressed interest in looking at all the uberon terms that have been part of submissions to date and looking at which are not in HCAO, then adding them to HCAO. Is this something that could be done?"

A: "yes we can force-import any Uberon term you'd like into HCAO if it's not there already. The missing Uberon terms can be listed in an HCAO ticket, then Zoë and I will take care of importing them by the nearest HCAO release. (The next one will be on April 20th, then May 17th.) There's just one thing I'd like to make sure of. I assumed that any Uberon term that's been part of HCA submissions would have been looked up in HCAO by the wranglers, and hence be in HCAO already. But perhaps this was not the case in early submissions and wranglers looked up Uberon directly? Also, the way that HCAO imports Uberon (i.e. the subset that's been imported) may have changed, so some anatomy terms that were in HCAO 2 years ago may not be there now.
Would you or Enrique (or others from your side) be preparing the list?"

Please add your comments here if any, and we'll go from there. Thank you!

**Comment by paolaroncaglia** [comment]
@ESapenaVentura @pnejad 
If there's any follow-up to your request [above](https://github.com/HumanCellAtlas/ontology/issues/104#issue-1188290166), and specifically if there's any existing Uberon anatomy term that isn't in HCAO at the moment and that you'd like to be imported in time for the April 20th HCAO release, please let me know by the end of tomorrow (Tue 12th). I'll be away April 14th-19th included, so I'm getting things ready for the HCAO release before I leave. Thank you!
Otherwise, feel free to reply to my questions [above](https://github.com/HumanCellAtlas/ontology/issues/104#issue-1188290166) when you have time, and we'll come back to this after the April release.

**Comment by ESapenaVentura** [comment]
@paolaroncaglia Apologies for the late reply! This did fly over my head and forgot to respond

I have created a ticket for the task above (preparing the list of terms) https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/743

Having it in our board, I will make sure that this list is completed ASAP (I have tagged you on the ticket so please feel free to comment)

Thanks for the reminder and the heads up, I'll make sure the other wranglers know about it!

**Comment by paolaroncaglia** [comment]
@ESapenaVentura sure, thank you.

**Comment by ESapenaVentura** [comment]
Hi @paolaroncaglia @dosumis !

I have done a quick search and found which UBERON terms we have in the HCA (In the file attached)

I would double check this because I just did a simple grep operation but to me, it looks like all the UBERON terms we have in our system are indeed in HCAO
[uberon_terms_in_hca.txt](https://github.com/HumanCellAtlas/ontology/files/8688816/uberon_terms_in_hca.txt)

**Comment by paolaroncaglia** [comment]
@ESapenaVentura thank you for providing the list of Uberon terms. We'll check next week and get back to you.

**Comment by paolaroncaglia** [comment]
@ESapenaVentura cc @pnejad 
Zoë checked earlier today, and all the Uberon terms from Enrique's file are indeed in HCAO (in the newest release to be precise, see https://github.com/ebi-ait/hca-ebi-dev-team/issues/487). 
Closing now, thank you!
