### ISSUE TITLE
[ENQ] What's the best Uberon term to associate to iPSCs?

### ISSUE THREAD

**Issue by paolaroncaglia** [HumanCellAtlas/ontology#105]
From a Slack thread between @pnejad and myself:

"Sometimes we have induced pluripotent stem cells as our cell lines and we need to list a model organ for them from uberon. What would be an ‘organ’ for iPSCs?"

"If the dataset, publication, or cell line "manufacturer" don't provide detailed info on how exactly the iPSCs were derived, you could go with [UBERON:0007023 'adult organism'](https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0007023). Based on the knowledge that iPSCs are generated from somatic cells coming from adult individuals/patients. I know it's a broad term, but if you need to list an anatomy term just for technical reasons, would that work? If not, I'd be happy to look at examples if you could send them to me please."

"We’ve been using embryo as the model organ for ipsc, since the pluripotent state is similar to early embryonic state. I feel like adult organism would imply that the differentiation has already occurred. Is there something we could use in place of embryo that could represent the pluripotent state?"

"It'd be helpful if you could please point me to a couple of public datasets/publications where I can look at the Materials & Methods sections. Also please to confirm, do you mandatorily have to use a term from Uberon? (Due to metadata schema etc.)"

"The hca metadata schema requires that we list model organs/the term to be from uberon for anatomy terms.
Example of a dataset with iPSCs that were cell lines: https://www.nature.com/articles/s41467-021-25328-6#Sec10
Another dataset that has been submitted to the HCA: https://stemcellsjournals.onlinelibrary.wiley.com/doi/full/10.1002/stem.3302"

**Comment by paolaroncaglia** [comment]
Notes to self (work in progress):
The first publication sends into a loop of looking up older references to see what organ/cell types the iPSCs were originally derived from (and note, if it's a cell type that won't work for HCA)
TBC

**Comment by paolaroncaglia** [comment]
@pnejad 
Please see my comment above about iPSCs. Thanks.

**Comment by pnejad** [comment]
Hi @paolaroncaglia, Thank you for looking into this. This works for me! I'll run it by the rest of the team to get their feedback as well.

**Comment by paolaroncaglia** [comment]
@pnejad 

> This works for me! I'll run it by the rest of the team to get their feedback as well.

Great, thanks. I'll leave this ticket open for a few days, so if there are any concerns, please feel free to add them here.

**Comment by paolaroncaglia** [comment]
@pnejad 
I'll close this ticket now, but if your team had any concern with my [suggestion on how to represent iPSCs](https://github.com/HumanCellAtlas/ontology/issues/105#issuecomment-1085695940), please feel free to re-open. Thank you.
