### ISSUE TITLE
[ENQ] Looking for a Mondo alternative to HP:0200067 'recurrent spontaneous abortion'

### ISSUE THREAD

**Issue by paolaroncaglia** [HumanCellAtlas/ontology#106]
@pnejad also asked:
"for disease, the ontologies have to be from Mondo or Pato (normal). I believe recurrent spontaneous abortion (HP:0200067) is in MONDO, but there is no MONDO ID for it. Is this normal?
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0200067"

**Comment by paolaroncaglia** [comment]
@pnejad 
'recurrent spontaneous abortion' (HP:0200067) is in Mondo because it's imported there, possibly due to some mapping. But it is still a term from an external ontology (HPO), hence it's not available in HCAO. I'll look into existing Mondo terms that you might use instead. Please feel free to provide links to datasets you need this for. Thanks.

**Comment by paolaroncaglia** [comment]
@pnejad 
Looking up HP:0200067 in Mondo using Ontobee shows you more clearly why the term is imported in Mondo (it's used in an axiom for the Mondo term [pregnancy loss, recurrent, susceptibility](https://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0000144):

 
![Screenshot 2022-04-01 at 11 17 53](https://user-images.githubusercontent.com/4982516/161234425-ad951d74-01f3-4635-b49e-167c405c141e.png)

**Comment by paolaroncaglia** [comment]
@pnejad 
Terms you could use:
[MONDO:0006774 'habitual spontaneous abortion'](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006774)
[MONDO:0041526 'pregnancy disorder with abortive outcome'](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0041526) (but it has a note "consider obsoleting")
Its parent [MONDO:0024575 'pregnancy disorder'](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024575)

**Comment by pnejad** [comment]
@paolaroncaglia  [MONDO:0006774](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006774)  sounds like a good fit for our dataset! Thank you

**Comment by paolaroncaglia** [comment]
@pnejad 

> [MONDO:0006774](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006774) sounds like a good fit for our dataset! Thank you

You're welcome! I'll close this ticket then.
