### ISSUE TITLE
[NTR] single-cell library preparation method: droplet-based single-cell RNA library preparation

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#107]
## Preferred term label
droplet-based single-cell RNA library preparation

## Textual definition
Droplet-based single-cell RNA library preparation method. 

## Suggested parent term
single cell library construction
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010183&viewMode=All&siblings=false

## Use case
single cell library construction method

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
I'll open an EFO ticket for this, and tag you there. I will then close this ticket as a duplicate, and will document everything in the EFO ticket instead. Thank you.

**Comment by paolaroncaglia** [comment]
@ami-day request moved to https://github.com/EBISPOT/efo/issues/1500. Thanks.

**Comment by paolaroncaglia** [comment]
@ami-day 
FYI, the new term is EFO_0030078 (droplet-based single-cell RNA library preparation).
Details are [here](https://github.com/EBISPOT/efo/issues/1500) if needed. Thanks.
