### ISSUE TITLE
Spreadsheet mapper for ontology annotations

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ontology#11]
As a data wrangler, I would like to submit a metadata spreadsheet to a service that uses Zooma 3 to map all ontologisable values in the metadata and returns the mapping summary to me. After reviewing and if necessary correcting any mappings, I would like to submit corrections back to Zooma to update the HCA knowledgebase.

**Comment by daniwelter** [comment]
Proposal here: https://docs.google.com/document/d/14jBaC1datf12WRQBCQcJ2kZ0OLp880ghw6oaJd0KPA4/edit?usp=sharing

**Comment by paolaroncaglia** [comment]
@dosumis 
Should this epic (and related tickets) be moved to a different HCA GitHub tracker? Thanks.

**Comment by paolaroncaglia** [comment]
@dosumis should this epic be updated to refer to OntoString?

**Comment by dosumis** [comment]
No longer applicable.
