### ISSUE TITLE
[ENQ] Import Gender term (NCIT) into HCAO 

### ISSUE THREAD

**Issue by Wkt8** [HumanCellAtlas/ontology#113]
@ESapenaVentura has been working to create a metadata-schema change to include 'gender' for the HCA metadata schema. There is a dataset from the TestesCellAtlas which contains samples from trans donors, and it is vitally important to record this metadata. 

The term we wish to import is 'Gender' [NCIT:C17357](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C17357). Please note that NCIT is not in the HCAO, so this may require some additional work. We would only need the 'Gender' term, and the terms beneath it in hierarchy. 

@zoependlington and @bvarner-ebi please let us know if you need more information. It would be great to get this into the July ontology release!

**Comment by ESapenaVentura** [comment]
Is there any advancements on this @bvarner-ebi ? is it going to be included in the next release?

**Comment by dosumis** [comment]
This will require additional work on the pipeline by @zoependlington so not sure it will make it into the next release (BTW - Will this be in addition to recording sex?)

**Comment by dosumis** [comment]
@zoependlington - could you comment on timescale? Might make sense to combine this with a push to make this more ODK-like.

**Comment by zoependlington** [comment]
I am hoping this is in scope for November, but will keep you up to date once I have more to update on. I have looked at the pipeline and it requires a little more work than first anticipated to update to more ODK-like, but there may be a temporary solution I can put in place if this addition is needed ASAP.
