### ISSUE TITLE
[NTR] stromal cell of thymus;  interstitial cell of thymus

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#114]
Please note this request is for 2 new linked terms, 1 of which is a parent and the other the child of the parent.

## Preferred term label

parent: stromal cell of thymus
child: interstitial cell of thymus

## Synonyms

parent: thymic stromal cell
child: thymic interstitial cell

## Textual definition

Parent: A stomal cell of the thymus.
Child: A cell that makes up the loose connective tissue of the thymus.

## Suggested parent term

Parent:
stromal cell
CL:0000499
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000499&lang=en&viewMode=PreferredRoots&siblings=false

Child:
stromal cell
CL:0000499
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000499&lang=en&viewMode=PreferredRoots&siblings=false

## Use case

Cell type ontology (CL) for cell types that are enriched for in the Human Cell Atlas.

**Comment by ami-day** [comment]
Hi @zoependlington 
Sorry I wasn't clear enough here.
The parent of 'interstitial cell of thymus' should be 'stromal cell of thymus'
The parent of 'stromal cell of thymus' should be 'stromal cell'
So, 2 new terms are being requested (stromal cell CL:0000499 already exists).
Does this help?

**Comment by ami-day** [comment]
> > Hi @bvarner-ebi
> > Sorry I wasn't clear enough here.
> > The parent of 'interstitial cell of thymus' should be 'stromal cell of thymus'
> > The parent of 'stromal cell of thymus' should be 'stromal cell'
> > So, 2 new terms are being requested (stromal cell CL:0000499 already exists).
> > Does this help?
> 
> Thank you for the clarification, @ami-day. Can you provide your references/sources for these cell types?

Hi @bvarner-ebi , I can provide the single-cell sequencing publication in which the authors enrich for certain cell type in the human Thymus  including "interstitial cell of thymus", here it is: https://www.nature.com/articles/s41467-020-20082-7. In this publication, they describe the fluorescence-activated cell sorting protocol and cell surface markers profiled to enrich for the interstitial cell of thymus cell type. Is this reference/source ok?

**Comment by bvarner-ebi** [comment]
@ami-day, pls see question below that came up during the PR review:

> are there other types of thymic stromal cell?
> totally understand if these need to be added and the others can wait kindda situation, just having single child parents is something to avoid (see https://douroucouli.wordpress.com/2022/01/04/ontotip-avoid-the-single-child-anti-pattern/)
> @shawntanzk, https://www.nature.com/articles/s41467-021-21346-6:
> "While recent evidence suggests that the thymic stroma is comprised of more functionally distinct subpopulations than previously appreciated, the extent of this cellular heterogeneity in the human thymus is not well understood.... The predominant stromal cells found in the postnatal thymus are thymic epithelial cells (TECs), mesenchyme, endothelium, and non-lymphoid hematopoietic cells (dendritic cells and macrophages)".
> 
> @ami-day, do you have any other thymic stromal cells you would like to add now?

**Comment by ami-day** [comment]
> @ami-day, pls see question below that came up during the PR review:
> 
> > are there other types of thymic stromal cell?
> > totally understand if these need to be added and the others can wait kindda situation, just having single child parents is something to avoid (see https://douroucouli.wordpress.com/2022/01/04/ontotip-avoid-the-single-child-anti-pattern/)
> > @shawntanzk, https://www.nature.com/articles/s41467-021-21346-6:
> > "While recent evidence suggests that the thymic stroma is comprised of more functionally distinct subpopulations than previously appreciated, the extent of this cellular heterogeneity in the human thymus is not well understood.... The predominant stromal cells found in the postnatal thymus are thymic epithelial cells (TECs), mesenchyme, endothelium, and non-lymphoid hematopoietic cells (dendritic cells and macrophages)".
> > @ami-day, do you have any other thymic stromal cells you would like to add now?

Hi @bvarner-ebi thank you for looking into this! Based on the articles you found, it looks like there are multiple thymic stromal cell types. Given this, and the aim of the HCA to identify previously unknown cell types, I think it makes sense to create the "stromal cell of thymus" node as a parent to "interstitial cell of thymus". I do not currently have any other thymic stromal cells in mind to add.

**Comment by bvarner-ebi** [comment]
Thank you, @ami-day.

Kindly note that the following classes have been added to CL:

CL:4030001 ‘stromal cell of thymus’
CL:4030003 ‘interstitial cell of thymus’
