### ISSUE TITLE
[NTR] choroidal neovascularization

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#115]
## Preferred term label

choroidal neovascularization

## Textual definition

Choroidal neovascularization describes the growth of new blood vessels that originate from the choroid through a break in the Bruch membrane into the sub–retinal pigment epithelium (sub-RPE) or subretinal space. Choroidal neovascularization (CNV) is a major cause of visual loss.

## Suggested parent term

eye disorder: MONDO:0005328

## Use case

To be used as a disease status label associated with donors and specimens (HCA metadata).

**Comment by bvarner-ebi** [comment]
Hi @ami-day, thank you for the new term request. Could you kindly provide a reference (PMID, doi, URL, etc) that supports the text definition?
If you also provide your ORCiD, we can attribute the definition to you.

**Comment by ami-day** [comment]
Hi @bvarner-ebi this is where I obtained the definition for "choroidal neovascularization": https://emedicine.medscape.com/article/1190818-overview.
I would prefer not to associate it with my ORCiD as I did not have a role in defining this disease state.

**Comment by dosumis** [comment]
@zoependlington - Assume we should request this from https://github.com/monarch-initiative/mondo/issues for import into EFO.

**Comment by zoependlington** [comment]
@dosumis It should be requested to Mondo, yes, although no need to import into EFO for HCA cases - they use the entirety of Mondo!

**Comment by ami-day** [comment]
Thank you!

**Comment by bvarner-ebi** [comment]
> Thank you!

My pleasure!
MONDO:0810000 'choroidal neovascularization' has been added to MONDO.
