### ISSUE TITLE
[NTR] Transvaginal ultrasound aspiration

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#116]
Transvaginal ultrasound aspiration

## Synonyms

oocyte retrieval
## Textual definition

Transvaginal ultrasound-guided oocyte retrieval, also known as egg retrieval, is a surgical technique used by medical professionals to extract mature eggs directly from the women’s ovaries under the guidance of ultrasound imaging.

## Suggested parent term

collecting specimen from organism - OBI:0600005

## Use case

collection protocol for embryonic samples obtained through frozen embryo donation

**Comment by bvarner-ebi** [comment]
Hi, @rachadele, thank you for the contribution. I will add this term to **EFO** for inclusion in the next HCAO release. 

- [ ] **Can you kindly provide a reference (PMID, doi, URL, etc) for the definition and/or your ORCiD?**

Do you agree to the following definition and synonym updates?

- [ ] **definition:** 
A surgical technique used by medical professionals to extract mature eggs directly from an ovary with the guidance of ultrasound imaging.

- [ ] **synonyms (broad):**
oocyte retrieval
egg retrieval

- [ ] **synonyms (exact):**
transvaginal ultrasound-guided oocyte retrieval

**Comment by rachadele** [comment]
my orcid id: 0000-0002-7431-4139
PMID reference: 2969085
yes, I agree to the term and synonym updates!

**Comment by bvarner-ebi** [comment]
Thank you, @rachadele!

Based on the PMID and re-reviewing the definition, may I suggest the label to be: 
'ultrasound-guided transvaginal needle aspiration of follicles' 
or 
'transvaginal ultrasound-guided oocyte retrieval' 
(whatever is not the label can be an exact synonym). 

The currently proposed label 'transvaginal ultrasound aspiration' suggests something broader than the proposed definition (it is not only limited to oocyte retrieval).

**Comment by rachadele** [comment]
Sure! I think "transvaginal ultrasound-guided oocyte retrieval" would  work best. Thank you!

**Comment by bvarner-ebi** [comment]
https://github.com/EBISPOT/efo/issues/1738

**Comment by bvarner-ebi** [comment]
@rachadele, thank you for your contribution.
The following term has been added to EFO and should be available in the next HCAO release:

EFO:0700009 'transvaginal ultrasound-guided oocyte retrieval'
