### ISSUE TITLE
[NTR] Oral rinse collection

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#117]
## Preferred term label

Oral rinse collection

## Textual definition

Oral rinse collection following rinse of the oral cavity.

## Suggested parent term

collecting specimen from organism
OBI:0600005
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0600005&lang=en&viewMode=All&siblings=false

## Use case

HCA Collection protocol

**Comment by bvarner-ebi** [comment]
Hi @ami-day, thank you for the contribution.

Can you kindly provide a reference for this term (PMID, doi, etc)? If none exists, could you provide your ORCiD and I will use that as the dbxref?

The definition uses the label in itself. Can you provide a definition that does not include the label or point to a reference we can use that can guide us in rewording it?

**Comment by ami-day** [comment]
> Hi @ami-day, thank you for the contribution.
> 
> Can you kindly provide a reference for this term (PMID, doi, etc)? If none exists, could you provide your ORCiD and I will use that as the dbxref?
> 
> The definition uses the label in itself. Can you provide a definition that does not include the label or point to a reference we can use that can guide us in rewording it?

Hi Bradley, A reference does not exist as this term is quite general. I would rather not associate it with my ORCiD as I had no role in defining "Oral rinse".

For the definition, how about the following:

"A saliva collection method where a solution such as a saline solution or other solution is used to rinse the mouth before collection of saliva."

**Comment by bvarner-ebi** [comment]
Hi @ami-day, thanks for the reply.

We typically annotate definitions with a source/reference so end-users can research what the term/class represents and editors can know how to use it in future modelling. These annotations do not impact the logical aspects of the class but are used to cross reference the definition so if others want to use it, they will know the source to confirm it represents what they intend to represent.
 
I imagine there was something (literature, dataset) that inspired this new term. Could you provide this reference or the ORCiD for the user who generated the definition for 'oral rinse collection'? If no reference is provided, the risk will be that the class may be modelled in the future in a way you did not intend.

**Comment by ami-day** [comment]
Hi @bvarner-ebi , in this case, i think it would make sense to reference the dataset that I am curating, in which saliva is collected from human donors by "oral rinse".  Here is the publication: https://doi.org/10.1038/s41591-021-01296-8

**Comment by ami-day** [comment]
Hi @bvarner-ebi is the above ok as a reference for the new ontology term?

**Comment by bvarner-ebi** [comment]
Hi, @ami-day, thank you for the reminder. I will review the reference and check it against the requested text definition.

To set expectations, kindly note that tickets assigned to me that are not directly related to the Cell Annotation Platform (CAP) are set to low priority since CAP is my primary project.

**Comment by ami-day** [comment]
> Hi, @ami-day, thank you for the reminder. I will review the reference and check it against the requested text definition.
> 
> To set expectations, kindly note that tickets assigned to me that are not directly related to the Cell Annotation Platform (CAP) are set to low priority since CAP is my primary project.

Ok good to know and no problem!

**Comment by bvarner-ebi** [comment]
Hi, @ami-day, I reviewed the [reference]( https://doi.org/10.1038/s41591-021-01296-8) provided, but cannot find mention of oral rinse collection. Collecting specimens via active drool collection is mentioned in this paper, but I don't see a specimen collection method mentioned that aligns with your definition.

Can you direct me to the relevant passage in the paper?

**Comment by ami-day** [comment]
Hi @bvarner-ebi ,

The Saliva data generated in this study was made available in a data portal, however, it remains unpublished and the collection and experimental methods were not included in the Methods in the publication text. We enquired about this data, and the authors have asked us to refrain from submitting this data until it has been published. I had found the saliva collection method in the portal metadata, but it looks like this particular dataset is now not available in their portal.

In terms of the formal definition, there was no available detailed description of the method, the description was simply "Collection by oral rinse"). I could not find an appropriate reference for a more formal definition. I therefore wrote the definition: "A saliva collection method where a solution such as a saline solution or other solution is used to rinse the mouth before collection of saliva." A more general definition could be: "A method to collect saliva from the mouth" or "Saliva was collected by oral rinse".

Which do you think would be most appropriate?

**Comment by bvarner-ebi** [comment]
Thank you for the background information, @ami-day!

In this case, I recommend using your ORCID as the dbxref since you are supplying the definition.
Once the reference becomes available, we could add it as a dbxref to the definition or revise the definition and references as needed.

**Comment by bvarner-ebi** [comment]
Thank you, @ami-day!
I should have this done by end of day Monday.

**Comment by bvarner-ebi** [comment]
Hi, @ami-day,

Thank you for the new term contribution. 
The following has been added to EFO and should be available in the next release:

EFO:0700013 'oral rinse collection'
