### ISSUE TITLE
Strip EBI branding of HCA-OLS instance

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ontology#12]
HCA OLS should largely conform to HCA branding and not display the EBI headers

**Comment by paolaroncaglia** [comment]
@dosumis 
Should this be implemented? If yes, who should this ticket be assigned to, please? Thanks.

**Comment by dosumis** [comment]
Postponed until HCA switches to using new containerised build OLS

**Comment by paolaroncaglia** [comment]
Reviewing old HCAO tickets; this one is still standing (see https://ontology.archive.data.humancellatlas.org/index).

**Comment by dosumis** [comment]
There's a long-standing agreement to switch to a containerised build which would fix this by default, as the containerised build lacks the branding.  One of the devs at HCA was talking to James about this task a few months back.  I'll try to chase up.
