### ISSUE TITLE
[NTR] immune cell

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#120]
## Preferred term label

immune cell

## Textual definition

A cell that is part of the immune system and helps the body fight infections and other diseases.

## Suggested parent term

animal cell
CL:0000548
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000548&lang=en&viewMode=PreferredRoots&siblings=false

## Use case

Cell type ontology (HCA)

**Comment by bvarner-ebi** [comment]
Hi @ami-day, can you kindly provide a reference for the source of this cell type (PMID, DOI, etc)?

Considering the parent term, would [CL:0000988 'hematopoietic cell' ](http://purl.obolibrary.org/obo/CL_0000988) be appropriate? Are there any 'immune cells' that would not be hematopoietic cells?

**Comment by ami-day** [comment]
> Hi @ami-day, can you kindly provide a reference for the source of this cell type (PMID, DOI, etc)?
> 
> Considering the parent term, would [CL:0000988 'hematopoietic cell' ](http://purl.obolibrary.org/obo/CL_0000988) be appropriate? Are there any 'immune cells' that would not be hematopoietic cells?

Hi @bvarner-ebi, here is a reference for the description: "https://www.cancer.gov/publications/dictionaries/cancer-terms/def/immune-cell"

Having looked through a number of specific immune cell ontologies as examples, I think CL:0000988 'hematopoietic cell' is suitable as the parent term.

**Comment by addiehl** [comment]
These include neutrophils, eosinophils, basophils, mast cells, monocytes, macrophages, dendritic cells, natural killer cells, and lymphocytes (B cells and T cells).

**Comment by bvarner-ebi** [comment]
Hi, @ami-day, checking in to confirm if the solution above will work for your use case. I am planning a CL release tomorrow, so if I get confirmation in time, the synonym updated will be incorporated in the next release.

**Comment by ami-day** [comment]
Hi @bvarner-ebi and @addiehl This sounds great, I agree I could use 'leukocyte' and that "immune cell" should be added as a related synonym. Thanks for your insight and swift response.

**Comment by bvarner-ebi** [comment]
Great, thank you for confirming, @ami-day. 
[This change has been made](https://github.com/obophenotype/cell-ontology/pull/1702) and will be reflected in the next CL release.
