### ISSUE TITLE
Library preparation for spatial transcriptomics [NTR] 

### ISSUE THREAD

**Issue by idazucchi** [HumanCellAtlas/ontology#121]
## Preferred term label
library preparation for spatial transcriptomics

## Textual definition
Library preparation step of a spatial trascriptomics assay

## Suggested parent term
library preparation
http://purl.obolibrary.org/obo/OBI_0000711

## Use case
This term will be used as general term for spatial trascriptomics library preparation

**Comment by bvarner-ebi** [comment]
Thank you for the ticket, @idazucchi. Can you provide a reference or your ORCID to add as a cross reference for this new term?

**Comment by idazucchi** [comment]
Hi @bvarner-ebi! This is my ORCID https://orcid.org/0000-0002-4900-7575

**Comment by bvarner-ebi** [comment]
Hi, @idazucchi,
Thanks again for the new term.

The following has been added to EFO and should be available in the next release:

EFO:0700012 'library preparation for spatial transcriptomics'
(https://github.com/EBISPOT/efo/pull/1789)
