### ISSUE TITLE
[NTR]  ECCITE-seq

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#124]
## Preferred term label

ECCITE-seq

## Synonyms

 Expanded CRISPR-compatible cellular indexing of transcriptomes and epitopes by sequencing

## Textual definition

CITE-seq and Cell Hashing adapted for compatibility with the 5P / V(D)J single cell kit from 10x Genomics, to allow researchers to perform sample multiplexing, doublet detection and protein detection together with 5’ gene expression and V(D)J reconstruction. In addition, through the addition of a custom RT primer and additional PCR reactions on the low molecular weight cDNA fraction, sgRNA capture and single cell CRISPR screens with multimodal readout are made possible.

[https://cite-seq.com/eccite-seq/](url)

## Suggested parent term

CITE-seq EFO:0009294

## Use case

Library preparation protocol

## Attribution

0000-0002-7431-4139

**Comment by bvarner-ebi** [comment]
@rachadele, thank you for the new term.

May I propose the following **text definition**:
"The collective capabilities of CITE-seq and Cell Hashing adapted for compatibility with the 5P / V(D)J single cell kit from 10x Genomics, to allow researchers to perform sample multiplexing, doublet detection and protein detection together with 5’ gene expression and V(D)J reconstruction."

The rest could be placed in a **comment**:
"Additionally, through the addition of a custom RT primer and additional PCR reactions on the low molecular weight cDNA fraction, sgRNA capture and single cell CRISPR screens with multimodal readout are made possible."

To match **synonym** casing seen in [CITE-seq](http://www.ebi.ac.uk/efo/EFO_0009294):
"expanded CRISPR-compatible cellular indexing of transcriptomes and epitopes by sequencing"

And, finally, to add the **synonym** as it appears in the reference:
"expanded CRISPR-compatible CITE-seq"

Kindly confirm if the above looks reasonable, and I will add the term to EFO.

**Comment by rachadele** [comment]
Looks good to me! Do you have an ETA for when the term will be added?

**Comment by bvarner-ebi** [comment]
Thanks for confirming, @rachadele. I will add this now so it should be included in the next EFO release and will confirm once completed.

**Comment by bvarner-ebi** [comment]
Hi, @rachadele, thank you for the new term.

The following has been added to EFO and should be available in the next EFO release:
EFO:0700014 ECCITE-seq
