### ISSUE TITLE
[ITR] BD Rhapsody Whole Transcriptome Analysis

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#127]
## Source ontology identifier
EFO:0700003

## Destination ontology

HCAO

## Preferred term label

BD Rhapsody Whole Transcriptome Analysis

## Textual definition

A BD Biosciences-based technology that sequences mRNA from the 3' end in an unbiased manner. [https://www.bdbiosciences.com/content/dam/bdb/marketing-documents/BD-Rhapsody-WTA-Amplification-Kit.pdf]()
## Suggested parent term

EFO:0010186 [single cell library construction](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010183)

## Use case
to be used in library preparation protocol schema

## Attribution

0000-0002-7431-4139

**Comment by bvarner-ebi** [comment]
Hi, @rachadele, thanks for the ticket.
This term appears in efo_slim.owl, which is part of the HCAO release. Can you clarify if something is missing?

**Comment by rachadele** [comment]
@willrockout can you help clarify why you thought we needed the terms added?

**Comment by willrockout** [comment]
@rachadele @bvarner-ebi I searched for it on the OLS site under the HCAO ontologies and nothing came up. @bvarner-ebi is there another spot to be able to search the efo_slim?

**Comment by bvarner-ebi** [comment]
Hi @willrockout, I don't believe any EFO term is found on OLS when just looking at HCAO. EFO terms are packaged separately in the HCAO release file in ontology/efo_slim.owl. That contains all the EFO terms that are part of the HCAO release.

If you download the release files and open the ontology/efo_slim.owl in Protégé or some other editor, you would be able to search that way.

**Comment by rachadele** [comment]
@bvarner-ebi thanks for clarifying!

**Comment by rachadele** [comment]
this term causes an error on ingest: `.library_construction_method.ontology : Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000711]`

**Comment by willrockout** [comment]
@bvarner-ebi Thanks for the clarification. I think this is a case where we need this term moved under EFO:0010183 single-cell library construction.

**Comment by bvarner-ebi** [comment]
@willrockout, can you confirm which option you are requesting:

'BD Rhapsody Whole Transcriptome Analysis' to be a child of 'single cell library construction' only 

or

'BD Rhapsody Whole Transcriptome Analysis' to be a child of 'single cell library construction' and 'single-cell RNA sequencing'

**Comment by willrockout** [comment]
@bvarner-ebi I think it should be moved under 'single cell library construction' only as the protocol is a library construction and doesn't include the sequencing step which is stated in the definition for single-cell RNA sequencing.

**Comment by bvarner-ebi** [comment]
@rachadele, @willrockout,

Thank you again for this ticket. 'BD Rhapsody Whole Transcriptome Analysis' has been **added** as a subclass under 'single cell library construction' and **removed** as a subclass from 'single-cell RNA sequencing' via PR https://github.com/EBISPOT/efo/pull/1938.

This change should be reflected in the next EFO and HCAO releases.
