### ISSUE TITLE
[ITR] BD Rhapsody Targeted mRNA

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#128]
## Source ontology identifier
EFO:0700004

## Destination ontology

HCAO

## Preferred term label

BD Rhapsody Targeted mRNA

## Textual definition

A BD Biosciences-based technology that utilizes multiplex PCR to sequence mRNA from the 3' end of specific genes from a predetermined panel. [ https://scomix.bd.com/hc/en-us/articles/360023293851-Targeted-mRNA-Protocols [https://www.bdbiosciences.com/en-us/products/reagents/single-cell-](https://www.bdbiosciences.com/en-us/products/reagents/single-cell-multiomics/targeted-kits)

## Suggested parent term
single cell library construction EFO:0010183

## Use case
to be used in library preparation protocol schema

## Attribution
0000-0002-7431-4139

**Comment by bvarner-ebi** [comment]
Hi, @rachadele, thanks for the ticket.
This term appears in efo_slim.owl, which is part of the HCAO release. Can you clarify if something is missing?

**Comment by rachadele** [comment]
@willrockout can you help clarify why you thought it wasn't in HCAO?

**Comment by willrockout** [comment]
@rachadele @bvarner-ebi Same as my other comment searched HCAO for the term nothing came up.

**Comment by rachadele** [comment]
@bvarner-ebi thanks for clarifying!

**Comment by rachadele** [comment]
this term causes an ingest error: .`library_construction_method.ontology : Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000711]
`

**Comment by willrockout** [comment]
@bvarner-ebi Similar to the other I think we need this term moved under EFO:0010183 single-cell library construction.

**Comment by bvarner-ebi** [comment]
@willrockout, can you confirm which option you are requesting:

'BD Rhapsody Targeted mRNA' to be a child of 'single cell library construction' only 

or

'BD Rhapsody Targeted mRNA' to be a child of 'single cell library construction' and 'single-cell RNA sequencing'

**Comment by willrockout** [comment]
@bvarner-ebi I think it should be moved under 'single cell library construction' only as the protocol is a library construction and doesn't include the sequencing step which is stated in the definition for single-cell RNA sequencing.

**Comment by bvarner-ebi** [comment]
@rachadele, @willrockout,

Thank you again for this ticket. 'BD Rhapsody Targeted mRNA' has been **added** as a subclass under 'single cell library construction' and **removed** as a subclass from 'single-cell RNA sequencing' via PR https://github.com/EBISPOT/efo/pull/1938.

This change should be reflected in the next EFO and HCAO releases.
