### ISSUE TITLE
Terms to describe lung collection location 

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ontology#13]
### Background
Pneumology nomenclature is used to describe the anatomy of the lung but this does not adequately describe where the samples in the airways were taken. A HCA contributor has the following requirements for his samples. There may be a way of modelling this without the need for new terms.

### New term requests:

`right lateral basal segment`
`left anterior segment`
`left apicoposterior segment`
`right anterior segment`
`right posterior segment`
`left medial basal / anterior segment`
Above terms are used alongside these terms to pinpoint meaning [bronchial biopsy|NCIT:C51782; lower lobe of right lung|UBERON_0002171; epithelium of segmental bronchus|UBERON_0002341]

`left superior segment`
`right posterior basal segment`
`right medial basal segment`
`right superior segment`
`right posterior segment`
`right medial segment`
`left posterior basal segment`
`left superior lingular segment`

Above terms are used alongside these terms to pinpoint meaning [bronchial brush biopsy\|EFO:0009125; left lung respiratory bronchiole\|UBERON_0003543; epithelium of bronchiole\|UBERON_0002051]

### HCAO also needs the following terms added or mapped to 
`biopsy of nose\|NCIT:C51626`
`biopsy of trachea\|NCIT:C51631`
`bronchial biopsy\|NCIT:C51782`

**Comment by hewgreen** [comment]
Feel free to take a quick look and let me know if you want me to chase down references. I'm not sure at the moment if we need new terms or not.

**Comment by hewgreen** [comment]
@daniwelter do you need any more information from Pascal about this?

**Comment by daniwelter** [comment]
We're working on a robot pipeline to get the terms into HCAO from FMA

**Comment by daniwelter** [comment]
Some issues with the Robot pipeline and Uberon at the moment. Will address this further once I'm back from holiday

**Comment by daniwelter** [comment]
These terms are now available in dev and will soon be deployed through all the environments
