### ISSUE TITLE
Add term for parenchymal cells to cell type ontology (CL)

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#15]
For new term requests, please provide the following information:

## Preferred term label

lung parenchymal cell

## Synonyms

none

## Textual definition

Any cell in the lung parenchyma which is the substance of the lung outside of the circulation system that is involved with gas exchange and includes the alveoli and respiratory bronchioles. Any cell from the tissue characteristic of lunch, as distinguished from associated connective or supporting tissues.

[citation 1](https://medical-dictionary.thefreedictionary.com/parenchymal+cell)
[citation 2](https://www.thefreedictionary.com/parenchymal+cell)
[citation 3](https://radiopaedia.org/articles/lung-parenchyma)

## Suggested parent term

[lung parenchyma](http://purl.obolibrary.org/obo/UBERON_0008946)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by malloryfreeberg** [comment]
@daniwelter would it be possible to prioritize this? Would like to use it with a dataset I wrangled that is otherwise ready to go (pending another schema update). Thanks!

**Comment by daniwelter** [comment]
This is one for @dosumis  - I have no edit access to CL.

**Comment by malloryfreeberg** [comment]
Cool. @dosumis? Could this be prioritized? Thanks!

**Comment by daniwelter** [comment]
@malloryfreeberg in preparation for submission to CL, could you list additional features of this cell type, eg surface markers, other cell types that it falls under, developmental lineage etc. Here's an example of the sort of thing CL would be looking for https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000570
Subclass of: 
- neurecto-epithelial cell
- serotonin secreting cell
- calcitonin secreting cell
- develops_from some migratory neural crest cell
- has plasma membrane part some neural cell adhesion molecule 1
- capable of some serotonin secretion
- capable of some calcitonin secretion
- part of some parenchyma of thyroid gland
- capable of some dopamine secretion

**Comment by malloryfreeberg** [comment]
Hmm, I'm not too sure about any of those features to describe that cell type. Let me check back in with the contributors who requested this cell type and see if they have any features to offer.

**Comment by dosumis** [comment]
> Any cell in the lung parenchyma which is the substance of the lung outside of the circulation system that is involved with gas exchange and includes the alveoli and respiratory bronchioles. Any cell from the tissue characteristic of lung as distinguished from associated connective or supporting tissues.

List of all cell types in the lung (currently in CL). 

'basal cell of epithelium of lobular bronchiole'
'basal cell of epithelium of respiratory bronchiole'
'basal cell of epithelium of terminal bronchiole'
'bronchioalveolar stem cell'
'bronchioalveolar stem cells'
'bronchus fibroblast of lung'
'brush cell of lobular bronchiole'
'brush cell of terminal bronchiole'
'epithelial cell of alveolus of lung'
'epithelial cell of lung'
'fibroblast of lung'
'lung ciliated cell'
'lung endothelial cell'
'lung goblet cell'
'lung macrophage'
'lung microvascular endothelial cell'
'lung neuroendocrine cell'
'lung secretory cell'
'mesothelial cell of visceral pleura'
'serous cell of epithelium of lobular bronchiole'
'serous cell of epithelium of terminal bronchiole'
pneumocyte
'type I pneumocyte'
'type II pneumocyte'


Your definition excludes blood supply and supporting tissues (e.g. mesothelium), so I suspect you want something that groups all of these apart from endothelial and meosthelial cells.  Is this correct?

Uberon has a term for 'lung parenchyma' but nothing in CL currently has a relationship to this, so I think the edit is to move all of the above apart from endothelial and mesothelial cells to have part relationships to this Uberon term and then make a grouping cell class for them all defined as 'any cell that is part of the lung parenchyma.'  Would that be OK?

**Comment by malloryfreeberg** [comment]
> Your definition excludes blood supply and supporting tissues (e.g. mesothelium), so I suspect you want something that groups all of these apart from endothelial and meosthelial cells. Is this correct?

I'm not sure about this one. I would ask this of Anna/Elo in the email so they can ask a lung expert.

> I think the edit is to move all of the above apart from endothelial and mesothelial cells to have part relationships to this Uberon term and then make a grouping cell class for them all defined as 'any cell that is part of the lung parenchyma.' Would that be OK?

This sounds fine to me.

**Comment by malloryfreeberg** [comment]
@danielsotirhos any update on getting this term into CL?

**Comment by danielsotirhos** [comment]
> @danielsotirhos any update on getting this term into CL?

Guessing this was a typo for @daniwelter or @dosumis ?

**Comment by malloryfreeberg** [comment]
> > @danielsotirhos any update on getting this term into CL?
> 
> Guessing this was a typo for @daniwelter or @dosumis ?

So sorry! Yes, was for @dosumis :) (stupid autocomplete)

**Comment by mshadbolt** [comment]
@zoependlington this is a term that I need to include in a dataset that I would like to submit soon, do you think you could pick this up and figure out whether we are likely to have this term added soon or if there is a reason no to add it?

**Comment by zoependlington** [comment]
@dosumis Is there any update on this term?

**Comment by dosumis** [comment]
Not clear that this is a term worth adding to CL if the tissue/organ type curated = uberon:'lung parenchyma’. The new term would simply be defined as:

Any cell that is part_of (some) Uberon:'lung parenchyma' 

Note - lung parenchyma itself is a very loose, general term covering multiple tissues (with many cell types).   On this basis,  every a new organ or tissue was added to the HCA/DCP, we could add a term for any cell in  that organ/tissue.  This would lead to a lot of bloating of CL and wouldn’t add any information to curation records.  

(Note - I had this conversation with curators back in April/May, but I'm having trouble tracking down where.  Apologies for not adding this to the ticket at the time.)

**Comment by dosumis** [comment]
(Note - it may still be worth editing Uberon to populate tissues under 'lung parenchyma')

**Comment by mshadbolt** [comment]
I discussed with @zoependlington and we decided that having 'lung parenchymal cell' when we already have 'lung parenchyma' as the organ part doesn't really add much information so I will close this ticket.
Will leave it up to @dosumis if he wants to make a ticket with regards to the work he mentions to populate tissues.
