### ISSUE TITLE
Add ontology for dissection (cadaver dissection) under OBI_0600005

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ontology#16]
## Preferred term label

dissection

## Synonyms

cadaver dissection

## Textual definition

sequential division of tissue layers to expose (and isolate) organs and organ parts of a deceased animal or plant

## Suggested parent term
Either organ extraction EFO_0009124
or one level up under collecting specimen from organism OBI_0600005

**Comment by daniwelter** [comment]
Dissection already exist in EFO (http://www.ebi.ac.uk/efo/EFO_0003856). I have reclassified the term to also fall under the specimen collection process and created a separate sub-class for cadaver dissection

**Comment by zperova** [comment]
@daniwelter  Great, thanks! I saw this one but assumed that it doesn't work since it is not under specimen collection. I will use this one in this case

**Comment by daniwelter** [comment]
Please don't close issues until we have successfully released EFO.
