### ISSUE TITLE
Add immunosurgery as collection method

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#17]
For new term requests, please provide the following information:

## Preferred term label

Immunosurgery

## Textual definition

A technique in which the outer layer (trophoblast) of a blastocyst is selectively destroyed by antiserum and complement, used especially to obtain the embryonic stem cells of the inner cell mass.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2557078/
https://en.oxforddictionaries.com/definition/immunosurgery

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

**Comment by daniwelter** [comment]
New term added http://www.ebi.ac.uk/efo/EFO_0009808
