### ISSUE TITLE
Add a term for 10x v3 sequencing

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ontology#18]
For new term requests, please provide the following information:

## Preferred term label

10x v3 sequencing

## Synonyms

10x v3

## Textual definition

10x v3 is the third version of the 10x sequencing technology.

## Suggested parent term
10x sequencing
http://www.ebi.ac.uk/efo/EFO_0008995

**Comment by daniwelter** [comment]
@zperova any chance at slightly more details for the definition? What differentiates v2 from v3? And v2 from v1 for that matter - I've been meaning to update the definition for ages.

**Comment by ambrosejcarr** [comment]
successive versions of the 10x chemistry use different barcode locations to improve the sequencing yield and quality of 10x experiments. 

For v2 vs v3, the following diagram details the main differences from an analysis perspective: 

![image](https://user-images.githubusercontent.com/5239152/57862788-eb836e80-77c6-11e9-81e5-c5902718d5ab.png)

[Reference](https://kb.10xgenomics.com/hc/en-us/articles/360000939852-What-is-the-difference-between-Single-Cell-3-and-5-Gene-Expression-libraries-)

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009898

**Comment by daniwelter** [comment]
@ambrosejcarr The next EFO release isn't actually until June 17th so the URI won't be publicly available until the 18th at the earliest. I only post the allocated ID on the ticket for the requester's information

**Comment by ambrosejcarr** [comment]
> @ambrosejcarr The next EFO release isn't actually until June 17th so the URI won't be publicly available until the 18th at the earliest. I only post the allocated ID on the ticket for the requester's information

Got it, thanks for the explanation.
