### ISSUE TITLE
Add term for 10X 3' v2 sequencing

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#19]
For new term requests, please provide the following information:

## Preferred term label

10X 3' v2 sequencing

## Synonyms

10X 3' v2

## Textual definition

10X 3' v2 is the second version of the 10x sequencing technology that sequences from the 3' end of nucleic acid molecules.

## Suggested parent term

[10X v2 sequencing](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009310)

**Comment by daniwelter** [comment]
@malloryfreeberg any chance at more details for the definition? How does the process differ for 3' v 5'?

**Comment by malloryfreeberg** [comment]
[Reference](https://kb.10xgenomics.com/hc/en-us/articles/360000939852-What-is-the-difference-between-Single-Cell-3-and-5-Gene-Expression-libraries-)

Question: What is the difference between Single Cell 3' and Single Cell 5’ Gene Expression libraries?

Answer: The two assays are similar but capture different ends of the polyadenylated transcript in the final library. Both solutions use polydT primer for reverse transcription, although in the 3' assay the polydT sequence is located on the gel bead oligo, while in the 5' assay the polydT is supplied as an RT primer. A template switching oligo (TSO) is used in both workflows to reverse transcribe the full-length transcript.

... This results in final 10x libraries that either represent the 3' end of the transcript (as the 10x Barcode is adjacent to the polyA tail on the 3' end of the transcript) or the 5' end of the transcript (as the the 10x Barcode is adjacent to the TSO and the 5' end of the transcript).

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009899
