### ISSUE TITLE
Add term for 10X 5' v2 sequencing

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#20]
For new term requests, please provide the following information:

## Preferred term label

10X 5' v2 sequencing

## Synonyms

10X 5' v2

## Textual definition

10X 5' v2 is the second version of the 10x sequencing technology that sequences from the 5' end of nucleic acid molecules.

## Suggested parent term

[10X v2 sequencing](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009310)

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009900
