### ISSUE TITLE
Add term for 10X v1 sequencing

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ontology#21]
## Preferred term label

10X v1 sequencing

## Synonyms

10X v1, 10X_v2

## Textual definition

10x v1 is the first version of the 10X sequencing technology. Differs from the other versions in the location and size of the barcodes.

## Suggested parent term

[10X sequencing](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008995)

## Use case

This term is necessary to capture datasets that use 10x kits with v1 chemistry, such as: 

- [E-MTAB-6967](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6967/)

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009897
