### ISSUE TITLE
Add term for 10X 3' v1 sequencing

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ontology#22]
## Preferred term label

10X 3' v1 sequencing

## Synonyms

10X 3' v1

## Textual definition

10x 3' v1 is the first version of the 10X sequencing technology that sequences from the 3' end of nucleic acid molecules. Differs from 5' v1 in the captured end from the polyadenylated transcript. 

## Suggested parent term

[10X v1 sequencing](https://github.com/HumanCellAtlas/ontology/issues/21) (Still not added to EFO database)

## Use case

This term is necessary to capture datasets that use 10x kits with 3' v1 chemistry , such as: 

- [E-MTAB-6967](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6967/)

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009901

**Comment by ESapenaVentura** [comment]
Thanks!

**Comment by daniwelter** [comment]
Please note that this ID should not be used until after the next EFO release - 17/06/19 - and subsequent HCAO rebuild
