### ISSUE TITLE
Add EDAM term for Count matrix

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#23]
For new term requests, please provide the following information:

## Preferred term label

Count matrix

## Synonyms

Raw count matrix; Read count matrix; Tag count matrix

## Textual definition

A table of unnormalized values representing summarised read counts per genomic region (e.g. gene, transcript, peak).

Modified description from [here](https://www.ebi.ac.uk/training/online/glossary/normalised-read-count-matrix).

## Suggested parent term

EDAM term under [Matrix](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_2082)

**Comment by daniwelter** [comment]
New term request https://github.com/edamontology/edamontology/issues/400
