### ISSUE TITLE
Add term for Quality control metrics

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#24]
For new term requests, please provide the following information:

## Preferred term label

Quality control metrics

## Synonyms

QC metrics

## Textual definition

Results of testing an output or a sample of an output against the desired specification or standard.

[Modified from citation](https://en.oxforddictionaries.com/definition/quality_control)

## Suggested parent term

EDAM term under [Report](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_2048)

**Comment by daniwelter** [comment]
@malloryfreeberg I would strongly recommend `Quality control report` as the preferred label for this term.

**Comment by malloryfreeberg** [comment]
@daniwelter that works for me. Can we add `Quality control metrics` as a synonym, then?

**Comment by daniwelter** [comment]
@malloryfreeberg I can suggest it - it's up to the editors whether they consider it a strict enough synonym.

**Comment by daniwelter** [comment]
https://github.com/edamontology/edamontology/issues/403
