### ISSUE TITLE
Add EDAM term for Alignment reference

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#25]
For new term requests, please provide the following information:

## Preferred term label

Alignment reference

## Synonyms

~Alignment reference sequence; Alignment reference profile; Alignment reference structure~

## Textual definition

One or a set of reference molecular sequences, structures, or profiles used for alignment of genomic, transcriptomic, or proteomic experimental data.

## Suggested parent term

EDAM term under [Data/Alignment](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_1916)

**Comment by daniwelter** [comment]
@malloryfreeberg The synonyms provided do not seem to be exact synonyms of each other and of the request terms, rather they appear to be sub-terms. EDAM only allows exact synonyms, ie they all have to be different names for the exact same thing.

**Comment by daniwelter** [comment]
https://github.com/edamontology/edamontology/issues/401

**Comment by malloryfreeberg** [comment]
@daniwelter That makes sense. Please ignore the suggested synonyms (will cross them out in the ticket).
