### ISSUE TITLE
Add a term for 10x 5' v3 sequencing

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#28]
For new term requests, please provide the following information:

## Preferred term label

10X 5' v3 sequencing

## Synonyms

10X 5' v3

## Textual definition

10X 5' v3 is the third version of the 10x sequencing technology that sequences from the 5' end of nucleic acid molecules.

## Suggested parent term

[10X v3 sequencing](https://github.com/HumanCellAtlas/ontology/issues/18)

**Comment by daniwelter** [comment]
@malloryfreeberg Are we confident that 5' v3 is actually a thing? Based on https://kb.10xgenomics.com/hc/en-us/articles/115003764132-How-does-cellranger-count-auto-detect-chemistry- and https://kb.10xgenomics.com/hc/en-us/articles/360000559571-How-can-I-remove-batch-effects-among-samples- and other help articles on the 10x genomics page, I'm not sure such a thing actually exists.

**Comment by malloryfreeberg** [comment]
> Are we confident that 5' v3 is actually a thing?

@kbergin @ambrosejcarr any thoughts?

**Comment by kbergin** [comment]
Asking our local PO who oversees 10X in the lab, she says it is a thing.

**Comment by ambrosejcarr** [comment]
The confusion may be that it is bundled with TCR profiling: https://support.10xgenomics.com/single-cell-vdj/datasets . There have been requests by the community to break it out as a general purpose kit separate from the TCR.

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009921 - provisional IRI, to be released 17/6/19, available from 18/6/19
