### ISSUE TITLE
Add a term for Slide-seq

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#29]
For new term requests, please provide the following information:

## Preferred term label

Slide-seq

## Synonyms

None

## Textual definition

A method for transferring RNA from tissue sections onto a surface covered in DNA-barcoded beads with known positions, allowing the locations of the RNA to be inferred by sequencing.

[paper citation](https://science.sciencemag.org/content/363/6434/1463)
[PubMed entry](http://www.ncbi.nlm.nih.gov/pubmed/30923225?dopt=Abstract)

## Suggested parent term

[RNA assay](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001457)

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009920
