### ISSUE TITLE
Ontology support for Common Coordinate Framework

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ontology#3]
CCF is a system to allow people to know if two different samples have come from the same location in different  peoples organs.  Use of ontologies has already been discussed in previous CCF meetings. 

The ontologists need to develop a robust proposal for how to provide ontology support for CCF.

**Comment by daniwelter** [comment]
Was HCA-141 + HCA-165

**Comment by dosumis** [comment]
No longer relevant
