### ISSUE TITLE
Add a term for SPLiT-seq

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#30]
For new term requests, please provide the following information:

## Preferred term label

SPLiT-seq

## Synonyms

None

## Textual definition

Split-pool ligation-based transcriptome sequencing (SPLiT-seq) is a single-cell RNA-seq method that labels the cellular origin of RNA through combinatorial barcoding.

[paper citation](https://science.sciencemag.org/content/360/6385/176)
[PubMed entry](https://www.ncbi.nlm.nih.gov/pubmed/29545511)

## Suggested parent term

[RNA assay](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001457)

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009919
