### ISSUE TITLE
Add a term for perfusion (specimen collection)

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#31]
For new term requests, please provide the following information:

## Preferred term label

perfusion

## Synonyms

None

## Textual definition

The passage of fluid through the lymphatic system or blood vessels to an organ or a tissue.
[citation](https://www.dictionary.com/browse/perfusion)

## Suggested parent term

[collecting specimen from organism](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0600005)

**Comment by daniwelter** [comment]
Based on the definition, this is not actually a specimen collection technique so the requested parent is not appropriate. From our available list of parent classes, I would suggest either [medical procedure](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002571) or directly as a child [experimental process](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002694)

**Comment by malloryfreeberg** [comment]
I'm trying to find a term to fill in for `collection_protocol.method` (from [this paper](https://www.sciencedirect.com/science/article/pii/S2405471216302666?via%3Dihub#sec4))for the following sample collection procedure:

"Mouse islets were isolated (and pooled) from five C57BL/6 and ICR mice by perfusion of the common bile duct with 0.8 mM Collagenase P (Roche), digestion of the pancreata with 0.8 mM Collagenase P (Roche) and purification of the islets by Histopaque gradient (Sigma) centrifugation."

On first read, it sounded like they perfused the bile duct with collagenase to "loosen" or collect the cells, but perhaps what they did was perfuse to remove any cruft and then digested the remaining pancreata for the cells? I'm not really sure what collection term to use in this case. Any thoughts?

**Comment by zperova** [comment]
Perfusion is used to get rid of the bile in the bile duct in this case. I would put that in the description, but the ultimate collection method is organ extraction followed by digestion and centrifugation. 

Perfusion is commonly used to get rid of the blood when one wants to fix the mouse brain for furter extraction.

**Comment by malloryfreeberg** [comment]
Thanks @zperova !

Closing this ticket.
