### ISSUE TITLE
Add a term for smFISH

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ontology#33]
## Preferred term label

smFISH
single-molecule fluorescence in situ hybridization

## Synonyms

none

## Textual definition

Single-molecule RNA FISH is a method for detecting individual RNA molecules within cells with short fluorescent labelled oligonucleotide probes via fluorescence microscopy.

[paper 1](https://science.sciencemag.org/content/280/5363/585)
[PubMed entry 1](https://www.ncbi.nlm.nih.gov/pubmed/9554849)
[paper 2](https://www.nature.com/articles/nmeth.1253)
[PubMed entry 2](https://www.ncbi.nlm.nih.gov/pubmed/18806792)

## Suggested parent term

[RNA assay](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001457)

**Comment by zperova** [comment]
technically all the other terms that have `FISH` in them should be a child term of this one - because they are based on this method.

**Comment by daniwelter** [comment]
http://www.ebi.ac.uk/efo/EFO_0009918
