### ISSUE TITLE
Add terms for file formats

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#35]
New terms to add to EDAM under Format:

# 1. Zarr

## Preferred term label

Zarr

## Synonyms

None

## Textual definition

The Zarr format is an implementation of chunked, compressed, N-dimensional arrays for storing data. ([citation](https://zarr.readthedocs.io/en/stable/index.html))

## Suggested parent term

[Binary format](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fformat_2333)

## Use case

Describing files produced by the data processing pipelines.

# 2. MTX

## Preferred term label

MTX

## Synonyms

None

## Textual definition

The Matrix Market matrix (MTX) format stores numerical or pattern matrices in a dense (array format) or sparse (coordinate format) representation. ([citation](https://reference.wolfram.com/language/ref/format/MTX.html))

Data represented: http://edamontology.org/data_3112|http://edamontology.org/data_2535

## Suggested parent term

[Textual format](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fformat_2330)

## Use case

Describing files produced by the data processing pipelines and/or matrix service.

# 3. Loom

## Preferred term label

Loom

## Synonyms

None

## Textual definition

The Loom file format is based on HDF5, a standard for storing large numerical datasets. The Loom format is designed to efficiently hold large omics datasets. Typically, such data takes the form of a large matrix of numbers, along with metadata for the rows and columns. ([citation](https://linnarssonlab.org/loompy/format/index.html))

Data represented: http://edamontology.org/data_3112|http://edamontology.org/data_2535

## Suggested parent term

[Binary format](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fformat_2333)

Possibly under [HDF5](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fformat_3590)?

## Use case

Describing files produced by the data processing pipelines and/or matrix service.

**Comment by daniwelter** [comment]
https://github.com/edamontology/edamontology/issues/404
https://github.com/edamontology/edamontology/issues/405
https://github.com/edamontology/edamontology/issues/406
