### ISSUE TITLE
Add term for Slide-seq

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ontology#38]
For new term requests, please provide the following information:

## Preferred term label

Slide-seq

## Synonyms

(e.g., Absent spleen)

## Textual definition

A method for transferring RNA from tissue sections onto a surface covered in DNA-barcoded beads with known positions, allowing the locations of the RNA to be inferred by sequencing. 

https://www.ncbi.nlm.nih.gov/pubmed/30923225

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

RNA assay
http://www.ebi.ac.uk/efo/EFO_0001457

## Use case

Please specify under what circumstances you anticipate this term being used in the HCA metadata.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by daniwelter** [comment]
Closing because this term already exists
