### ISSUE TITLE
As a data consumer, I want information that tracks cell stage development through a lineage, in order to investigate hematopoietic cells

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ontology#4]
Considerations relating to this include:

Coverage survey  in UBERON and CL of the relationship in the differentiation from one cell type to another cell type in an in vivo cell lineage. CL utilises the object properties such as ‘develops from’, ‘develops into’, ‘developmentally contributes to’, ‘developmentally preceded by’, ‘developmentally related to’, or ‘developmentally succeeded by’. Ingest-ontology should examine if the available axioms are sufficient for the HCA prioritised cell types (immune and blood cells, and brain cells), and if we have a schema that captures the transition of the cell lineage differentiation. This may be related to cell stages/phasing, but is not cell stages/phasing itself.

**Comment by daniwelter** [comment]
Was HCA-258

**Comment by dosumis** [comment]
@mshadbolt  - is this still relevant?  We have developmental relationships in CL & could make sure these are displayed.

**Comment by mshadbolt** [comment]
I don't really know what this is about, was created before I started at HCA, I would imagine by now we could just close it and start a new ticket if we want to address it again.
