### ISSUE TITLE
Add Afp-GFP mouse strain to EFO

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#40]
## Preferred term label

Afp-GFP

## Textual definition

Mouse strain --> Afp-GFP , information about this mouse can be found in the paper: https://www.nature.com/articles/s41586-019-1127-1

The paper cites another paper that calls the strain Tg(Afp‐GFP), I'm not sure which would be more appropriate to add.

https://onlinelibrary.wiley.com/doi/full/10.1002/dvdy.20843

**Comment by pnejad** [comment]
@willrockout

**Comment by zoependlington** [comment]
I added Afp-GP as the main label and Tg(Afp-GFP) as the synonym with references to both papers.

It'll be available (EFO_0010081) in the next release.

**Comment by pnejad** [comment]
@zoependlington Thank you! Is it Afp-GP or Afp-GFP?

**Comment by zoependlington** [comment]
@pnejad Sorry, typo on my behalf in that reply. It's Afp-GFP :-)
