### ISSUE TITLE
Visceral endoderm needs importing in next release

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#41]
Not sure which format to follow for this type of ticket, but it is based on discussions in ticket #39 

Comment from Dani: "visceral and definitive endoderm - UBERON:0004877 (needs importing in next release - please file a ticket) and UBERON:0005439".

**Comment by pnejad** [comment]
@zoependlington  Please let me know if you need more information for this ticket! Also tagging co-wrangler @willrockout.

**Comment by zoependlington** [comment]
@pnejad @willrockout Added, will be in the next release (which I'm hoping will be the 19th September).
