### ISSUE TITLE
Need help with mapping to correct ontologies for kidney snRNA-seq dataset

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#42]
@zoependlington (or @zperova ?) could you help me map my fields to the correct ontologies? I'm unsure about some, but I've attempted to map some myself -- please let me know if any are incorrect!

- ethnicity = Non-Hispanic White = HANCESTRO:0005 (european) ?
-----------
donor disease
- Renal mass = ?
- Acoustic neuroma = MONDO:0001569 ?
- OSA = MONDO:0007147 ?
- Hypertension = ?
- AKI = ?
- pleural effusion = ?
- benign prostatic hyperplasia = MONDO:0010811 ?
- diverticulitis = MONDO:0004235 ?
- anxiety = MONDO:0005618 ?
- depression = ?
- arthritis = MONDO:0005578 ?
- GERD = MONDO:0007186 ?
- lyme disease = MONDO:0019632 ?
- right renal mass = ? 
- type 2 diabetes = MONDO:0005148 ? 
- adrenal mass = MONDO:0007186 ?
- NASH = MONDO:0013209 ?
- hemochromatosis = ?
- SVT = ?
- IBS = MONDO:0005052 ?
- chest discomfort = ? (I'm leaning towards removing this from the list)
- hiatal hernia = MONDO:0007721 ? 
- prostate cancer = MONDO:0008315 ?
- dyslipidemia = ?
- hx VRE infection = ?
- PAF = MONDO:0018608 ?
- hyperlipidemia = MONDO:0021187 ?
-----------
- collection method = section = EFO:0009744 ?

**Comment by mshadbolt** [comment]
I'm not expert but maybe some of these would work:

[hypertensive disorder:MONDO_0005044 ](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0005044) - there are more specific child terms of this

hereditary hemochromatosis: [MONDO_0006507](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006507) 

AKI is listed as a synonym for [acute kidney failure:MONDO_0002492](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002492)

[depressive disorder:MONDO_0002050](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002050)

[ventricular tachycardia:MONDO_0005477](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005477)

Maybe [kidney neoplasm ](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0021163)would work for renal mass if you don't know further information about the kind of tumor it is? 

[inherited lipid disorder:MONDO_0002525](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002525) has dyslipidemia as a synonym

maybe pleural effusion would be either [pleurisy](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000986) or [pleuropneumonia](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001940)? or maybe there needs to be a new term, there is already a [pericardial effusion](https://ontology.staging.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001370)  but doesn't seem to be one for pleura

**Comment by zoependlington** [comment]
Renal mass = EFO_0003865 (if no other information is provided)
Acoustic neuroma = EFO_0000693 (is a synonym of this term, but I am not 100% convinced)
OSA = EFO_0003918
Hypertension = EFO_0000537
AKI = HP_0001919 (acute kidney injury?)
pleural effusion = EFO_0009637
benign prostatic hyperplasia = EFO_0000284
diverticulitis = EFO_1001460
anxiety = EFO_0005230
depression = EFO_0007634 (again not 100%, thoughts?)
arthritis = EFO_0005856
GERD = EFO_0003948
lyme disease = EFO_0008510
right renal mass = see renal mass
type 2 diabetes = EFO_0001360
adrenal mass = EFO_0003850 (potentially?)
NASH = EFO_1001249
hemochromatosis = EFO_1000642
SVT = HP_0004755
IBS = EFO_0000555
chest discomfort = could be HP_0100749 (definition is an unpleasant sensation characterised by physical comfort... localised to the chest)
hiatal hernia = HP_0002036
prostate cancer = EFO_0000673 currently has the synonym of prostate cancer but is probably not ideal, we can discuss this?
dyslipidemia = HP_0003119
hx VRE infection = may need new term
PAF = MONDO:0018608 ???
hyperlipidemia = EFO_0003774

section = EFO:0009744

**Comment by pnejad** [comment]
@zoependlington  Thank you for looking over this! I submitted this dataset already (part of the czi travel incentive). I will compare your suggestions with what I submitted and then do an AUDR next month after the meeting:)
