### ISSUE TITLE
Add term for EasySep live/dead separation

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#43]
## Preferred term label

EasySep cell separation (?)

## Synonyms

?

## Textual definition

Cells are targeted for either removal (negative selection and depletion) or selection (positive selection) using antibody complexes directed to specific cell surface antigens. The antibody complexes link targeted cells to EasySep™ magnetic particles. Labeled cells are pulled to the sides of the tube when the sample is placed in an EasySep™ magnet. Magnetically labeled cells will remain in the tube while the untouched cells can be simply poured or pipetted off into a new tube.

## Suggested parent term

sample enrichment `EFO:0009106`
assay - `OBI:0000070`
both?

## Use case

To describe an enrichment protocol method that uses this assay

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
New term ID is EFO_0010175. Term will be available after the next release.
