### ISSUE TITLE
Add 2 new terms to collection method

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#44]
For new term requests, please provide the following information:

## Preferred term label

- oophorectomy
- tonsillectomy

## Synonyms

- oophorectomy --> ovariectomy 

## Textual definition

- oophorectomy --> surgical removal of an ovary or ovaries

- tonsillectomy --> a surgical procedure in which both palatine tonsils are fully removed from the back of the throat

## Suggested parent term

[collecting specimen from organism](https://ontology.dev.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0600005)

## Use case

We have two "in-progress" datasets that require these terms so that we can best capture their experimental steps.

## Attribution

0000-0002-3163-0115

**Comment by zoependlington** [comment]
The new term IDs are:
oophorectomy --> EFO_0010173
tonsillectomy --> EFO_0010174

These will be available after the next release.
