### ISSUE TITLE
Jiarui data set library prep ontologies

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/ontology#45]
For new term requests, please provide the following information:

library construction method ontology_label and id for Seq-Well, CEL-Seq2, and sci-RNA-seq to below this term OBI_0000711

## Preferred term label
sci-RNA-seq needs a term 

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

Jiarui dataset

**Comment by zperova** [comment]
@cjvillar It looks like your changes did get saved in this ticket.

**Comment by zoependlington** [comment]
@cjvillar Could you provide a description for the new term for sci-RNA-seq please? And any references to papers etc. Thanks!

Also just to confirm, you would like all adding as a child of library preparation?

**Comment by cjvillar** [comment]
Hi Zoe,
Here is a good description: https://teichlab.github.io/scg_lib_structs/methods_html/sci-RNA-seq.html

Here is a paper: https://science.sciencemag.org/content/357/6352/661

Yes, please add this as a child of lib prep (OBI_0000711)

**Comment by zoependlington** [comment]
sci-RNA-seq is http://www.ebi.ac.uk/efo/EFO_0010550.

Everything you've requested is also now sitting under library preparation.

You should see this after the next release (17th December).
