### ISSUE TITLE
Add new cell type

### ISSUE THREAD

**Issue by tianap** [HumanCellAtlas/ontology#49]
For new term requests, please provide the following information:

## Preferred term label

CD34-positive hematopoietic stem cell

## Synonyms

CD34+ HSC

## Textual definition

CD34-positive hematopoetic stem cell is a hematopoetic stem cell that is CD34-positive.

## Suggested parent term

hematopoietic stem cell
https://ontology.staging.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000037

## Use case

This is a new cell type for one of the GEO datasets we are wrangling.

**Comment by zoependlington** [comment]
@dosumis One for CL.

**Comment by paolaroncaglia** [comment]
@tianap (cc @dosumis as he was assigned previously)
Would the existing term [CL:0001024 CD34-positive, CD38-negative hematopoietic stem cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001024) fit your need?
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

I suspect that the submitter was an intern in your group previously? The term CL:0001024 'CD34-positive, CD38-negative hematopoietic stem cell' is already in HCAO, so I'll close this ticket. If a different term was needed instead (no ID for the GEO dataset was provided, so I can't double-check), please open a new ticket. Thanks!

Paola

**Comment by pnejad** [comment]
Thank you @paolaroncaglia
