### ISSUE TITLE
10X V(D)J sequencing

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#51]
We may need to do some further research on the scope of terms we need to add to capture this technology as well as where they would sit within the hierarchy of 10X terms.

I am not sure if it is worth also creating more specific terms for each type of cDNA enrichment for T cell and B cell sequences?

Have any other stakeholders thought about what kind of ontologies might be needed to capture experiments from this technology?

Have put some suggestions below but would be good to get a second opinion on whether they seem reasonable

## Preferred term labels

Some possibilities:

10X 5' v2 V(D)J sequencing
    10X 5' v2 TCR sequencing
    10X 5' v2 Ig sequencing 

## Synonyms

10X immune profiling, 10X VDJ, Chromium V(D)J

## Textual definition

10X 5' v2 V(D)J sequencing:
This method creates libraries that can capture gene expression, V(D)J sequences and feature barcodes from the same cells depending on the type of enrichment used. 

## Suggested parent term

10X 5' v2 sequencing
http://www.ebi.ac.uk/efo/EFO_0009900

## Use case

To fill in the `library_preparation_protocol.library_construction_method` field

## Attribution

0000-0001-7505-5418

**Comment by zoependlington** [comment]
@mshadbolt Would you like the three suggested terms adding, or are you still in discussion for which terms are required?

**Comment by mshadbolt** [comment]
Hi @zoependlington I was hoping to get some advice because I'm not really sure what the best term would be. Is there a technology expert that the ontology usually consults with when adding new terms?

**Comment by zoependlington** [comment]
@mshadbolt I will bring this up in our next EFO meeting so we have a wider opinion and may be able to find someone who is expert enough to advise on this.

**Comment by mshadbolt** [comment]
That sounds great, thanks Zoe!

**Comment by mshadbolt** [comment]
Just remembering some of these old tickets... @zoependlington did you manage to get any expert opinion about V(D)J sequencing?

thanks

**Comment by mshadbolt** [comment]
@zoependlington @dosumis although I am still not very confident in exactly how it should be modelled I think it would be get some ontology terms into the hcao so we have something to work with and worry about editing them later if it is not fully correct.

My suggestion would be a hierarchy as follows
10X 5' v2 sequencing: EFO_0009900
  | - 10X Immune profiling
     | - 10X TCR enrichment
     | - 10X Ig enrichment

10X Immune profiling 
This method creates libraries that can capture gene expression, V(D)J sequences and feature barcodes from the same cells depending on the type of enrichment used.

10X TCR enrichment
This method enriches 10X 5' gene expression libraries with alpha and beta chain T cell receptor (TCR) sequences using PCR primers.

10X Ig enrichment
This method enriches 10X 5' gene expression libraries with heavy and light chain Immunoglobulin (Ig) sequences from B cells using PCR primers.

**Comment by zoependlington** [comment]
@mshadbolt I can add them as per your suggestion. I did not hear back from those I reached out to for opinion, but I can send another message just to double check. In this case, these will be available in the mid-May release. 

Are there any x-refs for these terms, e.g. PMID? or synonyms you're aware of? Thanks.

**Comment by mshadbolt** [comment]
Hi Zoe thanks for this. I edited the post to hopefully see the hierarchy better but i would want the immune profiling term as a sub term under the 5' v2 sequencing, and the immune profiling term two enrichment terms under that.

I don't think there is a particular publication that defines the technique, would it be worth linking to the 10X page? https://www.10xgenomics.com/products/vdj/?src=search&lss=google&cnm=sem-goog-2020-website-page-ra_g-p_brand-emea&cid=7011P000000oWxB

A synonym for `10X Ig enrichment` could be `10X BCR enrichment`

**Comment by zoependlington** [comment]
- 10X Immune profiling (EFO_0010713)
- 10X TCR enrichment (EFO_0010714)
- 10X Ig enrichment (EFO_0010715)

All in EFO and will be imported into HCAO after the EFO release. I'll try and release HCAO mid-next week, so you'll see them then.
