### ISSUE TITLE
Add peripheral and central retina terms

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ontology#52]
For new term requests, please provide the following information:

## Preferred term label

peripheral retina

central retina

## Textual definition

Peripheral retina - region of retina that extends from central retina to ora serrata. Peripheral retina is dominated by rods and also has less ganglion cells and is not as thick as central retina. It is responsible for peripheral and night vision.
Link: https://webvision.med.utah.edu/book/part-i-foundations/simple-anatomy-of-the-retina/

Central retina - region of retina around the fovea that extends approximately for 6 mm. Central retina is considerably thick due to increased density of photoreceptors, particularly cones and their associated bipolar and ganglion cells. 
Link: https://webvision.med.utah.edu/book/part-i-foundations/simple-anatomy-of-the-retina/

## Suggested parent term
retina - UBERON:0000966
https://ontology.staging.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000966

## Use case

Currently there is no way to indicate the difference between central and peripheral retina while these parts of retina have different structure and function. 

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Hi @zperova, is [this](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0013682&viewMode=All&siblings=false) term good for peripheral retina? If so I can import this into HCAO.

I'll have to request the central retina term from UBERON.

**Comment by zperova** [comment]
@zoependlington Could the description be updated?

**Comment by zoependlington** [comment]
@zperova I'll create a ticket and as UBERON to update to the above :-)

**Comment by zoependlington** [comment]
@zperova Just an update (I haven't forgotten about this ticket, promise!): The new term and the updated definition are done, just waiting for a new release of UBERON and then they will be pulled into HCAO.

**Comment by zperova** [comment]
thanks @zoependlington

**Comment by zoependlington** [comment]
@zperova Just an update, I'm still waiting for an UBERON release with these changes/additional term to pull into HCAO. Unfortunately the last release was in November (that I can see on OLS anyway) and so there has been no update since. I'll keep an eye on it and as soon as I can, I'll pull them into HCAO.

**Comment by zperova** [comment]
thanks for the update @zoependlington !

**Comment by dosumis** [comment]
The last Uberon release was about a month ago, so should now be available

![image](https://user-images.githubusercontent.com/112839/96024056-2b7ed300-0e4b-11eb-9136-66dc017d9d20.png)

**Comment by paolaroncaglia** [comment]
Summary: the term that's still needed for this ticket (UBERON:8000004 central retina) wasn't imported in the HCAO release dated 2020-10-26. Pinning this ticket for discussion with @zoependlington at our next meeting.

**Comment by paolaroncaglia** [comment]
Update: Zoe and David modified the HCAO pipeline to overcome issues like this one. Zoe and I will meet late-next week and will see that UBERON:8000004 central retina gets imported in the HCAO release scheduled for then.

**Comment by paolaroncaglia** [comment]
@zperova 
The term UBERON:8000004 central retina is now in the HCAO release. It will be visible in public OLS in a day or so. Thanks,
Paola
