### ISSUE TITLE
Incorrect definition of cadaver dissection 

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ontology#53]
In the following term's definition:
cadaver dissection
http://www.ebi.ac.uk/efo/EFO_0009807 

replace `animal or part` to `human body` for the definition to read: 
`sequential division of tissue layers to expose (and isolate) organs and organ parts of a deceased human body`

**Comment by zperova** [comment]
@zoependlington I made a mistake in the original ticket for this term: https://github.com/HumanCellAtlas/ontology/issues/16
 Could you please help to fix it?

**Comment by zoependlington** [comment]
Of course @zperova. I just released EFO today so unfortunately this won't appear in tomorrow's HCA ontologies release but I'll make sure it's done for the January release.

**Comment by zperova** [comment]
oh, I thought it would be tomorrow @zoependlington

**Comment by zoependlington** [comment]
@zperova The HCAO release is tomorrow, but I have to make the edits in EFO which releases on the 15th or the next working day so that was released today and will then be pulled into the HCA ontology release tomorrow. Please let me know if this is breaking or if it's okay to appear in the January release. :-)

**Comment by zperova** [comment]
thanks @zoependlington I will make a note for myself for the future!

**Comment by zoependlington** [comment]
@zperova All done. This will be released in the EFO release tomorrow and then pulled into the HCAO release on Monday.

**Comment by zperova** [comment]
Thanks @zoependlington Should I close it now or wait until Monday?

**Comment by zoependlington** [comment]
I'll close once EFO is successfully released, thanks @zperova
