### ISSUE TITLE
Add zone of organs and children to the HCAO

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#54]
As discussed in #48 UBERON currently lacks some of the finer grained zones that are present in the FMA ontology. For the following organs would it be possible to add the `zones` under the UBERON organ/organ part parent to give us the ability to specify more specific regions of organs?

The one reservation I have about this is whether this will lead to inconsistencies in our data, so if there is an equivalent term in UBERON is there a way of making these equivalent somehow?

- Zone of kidney (`FMA:86310`) http://purl.obolibrary.org/obo/FMA_86310
- Zone of small intestine (`FMA:14092`) http://purl.obolibrary.org/obo/FMA_14092 
- Zone of large intestine (`FMA:86175`) http://purl.obolibrary.org/obo/FMA_86175
- Zone of uterine tube (`FMA:18302`) http://purl.obolibrary.org/obo/FMA_18302
- Zone of uterus (`FMA:17559`)  http://purl.obolibrary.org/obo/FMA_17559
- Zone of bone organ (FMA:10483) http://purl.obolibrary.org/obo/FMA_10483
- Intercostal muscle (FMA:13354) http://purl.obolibrary.org/obo/FMA_13354
- Segment of tracheobronchial tree (FMA:12224) http://purl.obolibrary.org/obo/FMA_12224
- Segment of trachea (`FMA:26659`) http://purl.obolibrary.org/obo/FMA_26659
- Subsegment of liver (`FMA:15725`) http://purl.obolibrary.org/obo/FMA_15725

@HumanCellAtlas/wranglers are there any other organs that you have struggled to find enough detail for when trying to assign an organ part for specimen from organ?

**Comment by zperova** [comment]
@mshadbolt there are UBERON terms for the following:
Zone of uterine tube `UBERON:0013515`: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0013515
Zone of bone organ `UBERON:0005913`: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0005913
Intercostal muscle `UBERON:0001111`: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001111&viewMode=All&siblings=false

**Comment by zoependlington** [comment]
Thanks @mshadbolt and @zperova! I'll make sure these are in HCAO for the January release. If there are any others, please feel free to continue commenting on this ticket.

**Comment by mshadbolt** [comment]
For intercostal muscle UBERON doesn't go into the detail of which intercostal muscle it samples, whereas CBTM specifically samples the muscle between ribs 2 and 3 and would like to capture this information

I will double check the others once our OLS is back up as I thought I struggled to find some terms last time I looked

**Comment by mshadbolt** [comment]
On example of bone that I would like added to our ontology that I think isn't there at the moment is the epiphysial plates of Tibia, Fibula and Femur

Epiphyseal plate of tibia http://purl.obolibrary.org/obo/FMA_33934
http://purl.obolibrary.org/obo/FMA_32792
https://www.ebi.ac.uk/ols/ontologies/fma/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFMA_34074

**Comment by zoependlington** [comment]
Reminder to self: 
http://purl.obolibrary.org/obo/UBERON_0000117 - respiratory tube (has synonym - segment of tracheobronchial tree)

**Comment by zoependlington** [comment]
@mshadbolt I've added the FMA 'zone of' terms, but not the epiphyseal plates as they require a little more looking into and potentially changes to the ontology build. I'll try to get them added before the February release. Please let me know if there are any others you would like added.

**Comment by mshadbolt** [comment]
hi @zoependlington sorry for the delay but just circling back to this now. I was having a look at the release and can see that as an example 'zone of kidney' has been added, but the main reason I wanted to add this term was to get its child terms, 'Superior pole of kidney' and 'Inferior pole of kidney' is there a way of also copying the child terms?

**Comment by zoependlington** [comment]
Hi @mshadbolt, apologies for the delay. I can absolutely add the children. They'll be available in the mid-May release, if that's okay?

**Comment by mshadbolt** [comment]
awesome thanks @zoependlington !

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
To speed things up, may I please ask you to summarise what terms from your original list are still missing in HCAO, and indicate if those are available in Uberon or FMA? 
In the example you mention for intercostal muscle (“UBERON doesn't go into the detail of which intercostal muscle it samples, whereas CBTM specifically samples the muscle between ribs 2 and 3 and would like to capture this information”), if that need hasn’t been addressed yet, we’d need to check with Uberon if they are ok to add such a specific child and restrict it to Homo sapiens or maybe primates (as the number of ribs varies across species). If not and if that level of detail is still necessary to HCA, I guess we could create an EFO term. 

@zoependlington if still missing, will the children of ’zone of kidney’ (‘Superior pole of kidney' and 'Inferior pole of kidney’) be automatically added in the next HCAO release, or do we need to specify that in the pipeline/build? 

Thanks both,
Paola

**Comment by paolaroncaglia** [comment]
@mshadbolt FYI, ‘Superior pole of kidney' and 'Inferior pole of kidney’ were indeed already added to HCAO.

**Comment by paolaroncaglia** [comment]
@mshadbolt Zoë released HCAO today, but the FMA terms listed in https://github.com/HumanCellAtlas/ontology/issues/54#issuecomment-566488227 are still missing due to a technical issue. We plan to address that before the next release.

**Comment by mshadbolt** [comment]
Ok great, thanks for letting me know

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Similarly to #59 , Zoe and David addressed the addition of FMA terms in this ticket, and all should be well. Keeping this ticket open so we can check after the next HCAO release scheduled for late next week. Thanks.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
All terms in this ticket are now in the HCA release. They'll be in public OLS in a day or so. Thanks.
