### ISSUE TITLE
Have Smart-seq and Smart-seq2 occur within single cell library construction

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#58]
Currently `Smart-seq: EFO:0008930` and `Smart-seq2: EFO:0008931` are within the EFO library preparation hierarchy but don't occur within `single cell library construction: EFO:0010183` when they are single cell library construction methods. I think they should either be moved or should also be in this part of the hierarchy. They should potentially come under `Smart-like: EFO:0010184` but will leave it up to an ontology expert to place them correctly

(https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711&viewMode=All&siblings=false)

**Comment by mshadbolt** [comment]
Also it seems like many of the techniques within `library preparation` are exclusively single cell methods so might be worth doing a general review to see which should be moved

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
I'll transfer this issue to the EFO tracker, and I'll assign it to myself to look into in the (hopefully near) future. Thanks.
