### ISSUE TITLE
Update cell ontology to include new terms

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#59]
@zoependlington I was just curating some cell types and I noticed that 
e.g. pulmonary ionocyte (https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017000&viewMode=All&siblings=false) exists in the EBI OLS but not in our own HCAO
![Screenshot 2020-04-27 at 15 54 14](https://user-images.githubusercontent.com/13007987/80386509-5fffd200-889f-11ea-801e-5b6fbd507153.png)

Can you please update for the new release? Not sure if there are any other terms that need to be added but if there is a way to check and update that would be grand!
Thanks!

**Comment by paolaroncaglia** [comment]
@mshadbolt 
It looks like this term is not in HCAO OLS yet. I made a note to discuss and address at my next meeting with @zoependlington and @dosumis , it falls in the broader context of establishing a procedure to ensure that all e.g. CL terms created for HCAO actually end up in HCAO (possibly via subset tags).

**Comment by paolaroncaglia** [comment]
@mshadbolt 
FYI: Zoe and David edited the HCAO pipeline and 'pulmonary ionocyte' should now be included in HCAO, but you'll need to wait until the next HCAO release, which is scheduled for next Thursday Dec 3rd. I'll leave this ticket open so we don't forget to check. Thanks.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
I confirm that 'pulmonary ionocyte' is now in the HCAO release. It'll be visible in public OLS in about a day. Thanks.
