### ISSUE TITLE
New ontology term request (HCA) - vacuum aspiration

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#60]
For new term requests, please provide the following information:

## Preferred term label

vacuum aspiration

## Synonyms

-aspiration
-suction aspiration

## Textual definition

Vacuum or suction aspiration uses aspiration to remove uterine contents through the cervix. It may be used as a method of induced abortion, a therapeutic procedure used after miscarriage, or a procedure to obtain a sample for endometrial biopsy (wikipedia).

## Suggested parent term

"collecting specimen from organism"
http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0600005

## Use case

Collection protocol: method of collecting specimen from organism

**Comment by zoependlington** [comment]
Thanks @ami-day! This term has been added to EFO and therefore will be pulled into HCA ontologies after the next EFO release (July).

For your future reference, here is the ID:
EFO_0010727 | vacuum aspiration
