### ISSUE TITLE
New ontology term request (HCA) - curettage

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#61]
For new term requests, please provide the following information:

## Preferred term label

curettage

## Synonyms

N/A

## Textual definition

Curettage, in medical procedures, is the use of a curette to remove tissue by scraping or scooping. Curettages are also a declining method of abortion. It has been replaced by vacuum aspiration over the last decade. Curettage has been used to treat teeth affected by periodontitis.

## Suggested parent term

"collecting specimen from organism"
http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0600005

## Use case

HCA collection protocol: method for collecting specimen from organism.

**Comment by zoependlington** [comment]
Thanks @ami-day! This term has been added to EFO and therefore will be pulled into HCA ontologies after the next EFO release (July).

For your future reference, here is the ID:
EFO_0010728 | curettage
