### ISSUE TITLE
subclinical neuro-inflammation

### ISSUE THREAD

**Issue by gjdrumm2000** [HumanCellAtlas/ontology#62]
For new term requests, please provide the following information:

## 

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

## GSE 127969

Please specify under what circumstances you anticipate this term being used in the HCA metadata.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Quick notes for self: need to clarify if the requested term ‘subclinical neuro-inflammation’ should be a child of EFO ‘disease staging’ (definition fits, though existing children are all related to cancer), or a phenotype. (Mondo has ‘neuronitis’, undefined, with a related synonym ‘neuroinflammation’ but a comment “Editor note: check this”.) Would the term apply to diseases other than MS?
The paper describing the GSE study in question is https://pubmed.ncbi.nlm.nih.gov/31566584/. Also potentially useful may be https://www.pnas.org/content/pnas/early/2020/08/13/2003339117.full.pdf?versioned=true.
Also, add synonyms “subclinical neuroinflammation” (exact) and “SCNI” (related or broad).

**Comment by paolaroncaglia** [comment]
Hi again @pnejad and @mshadbolt ,

May I ask for your feedback here too please. @zoependlington and I think that the requested term above should be a disease stage term based on the proposed definition, and I plan to add it in EFO by the next release like that unless you have any objection or advice. Please let me know if you disagree.

Thanks,
Paola

**Comment by mshadbolt** [comment]
I thought our schema requires that disease terms that we use should be a part of MONDO. we only allow EFO for the 'normal' term that we use when there is no disease recorded for a speciment.

**Comment by paolaroncaglia** [comment]
Thanks @mshadbolt . That's correct, disease terms should come from Mondo, but this would be a disease stage term. Mondo doesn't have those. :-)

**Comment by pnejad** [comment]
@paolaroncaglia What would be the correct mondo ontology to use for this field in our metadata? We need to put something down for disease (coming from Mondo). Is there something close to it?

**Comment by paolaroncaglia** [comment]
@pnejad and @mshadbolt 

> @paolaroncaglia What would be the correct mondo ontology to use for this field in our metadata? We need to put something down for disease (coming from Mondo). Is there something close to it?

From the Methods section of PMID:31566584:
“Study subjects and procedures. … Inclusion criteria for study participation were met for monozygotic twins with an MS diagnosis … Monozygotic twin pairs with clinical discordance for MS … For inclusion in the present analysis, CSF samples had to be available of either both co-twins or the clinically healthy co-twin only, resulting in 4 monozygotic twin pairs and 4 additional clinically healthy co-twins with signs of SCNI in MRI and/or CSF. … CSF samples from control subjects with encephalitis (Enc) and noninflammatory controls (NIC) were provided …”
If I’m interpreting your metadata annotation needs correctly, you’ll have the following cases:

co-twin with diagnosed multiple sclerosis => MONDO:0005301 multiple sclerosis
clinically healthy co-twin (no sign of SCNI) => no disease annotation
clinically healthy co-twin with signs of SCNI => see below
control subject with encephalitis => MONDO:0019956 encephalitis
noninflammatory control => no disease annotation

Ideally one would want to use a phenotype term to describe a “clinically healthy co-twin with signs of SCNI”, but there are a couple of Mondo terms you could use:

- MONDO:0004466 neuronitis, has related synonym neuroinflammation and is an inflammatory disease located in neurons. It comes from UMLS and DOI~D and has an editor’s note to check the term.
- MONDO:0015144 brain inflammatory disease, i.e. an inflammatory disease located more generally in the brain.

I think the latter is broader but safer.
Please let me know if you agree. If so, no term needs to be created in EFO or elsewhere and this ticket can be closed. Thanks!

**Comment by pnejad** [comment]
Thank you @paolaroncaglia

**Comment by pnejad** [comment]
Needs a new collection method ontology


micropuncture fluid collection | MMO:0000637
-- | --
