### ISSUE TITLE
New ontology term request (HCA) - chorionic villus

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#63]
For new term requests, please provide the following information:

Please note that the term is available in the OLS but it is not available as a valid HCA metadata term.
http://purl.obolibrary.org/obo/UBERON_0007106

## Preferred term label

chorionic villus

## Synonyms

fetal part of placenta
chorionic villus
placental villous
villous chorion
fetal placenta
placental villus
chorionic villous
chorionic villi
embryonic placenta
villous of placenta
embryonic part of placenta
placental villi

## Textual definition

One of the minute vascular projections of the fetal chorion that combines with maternal uterine tissue to form the placenta.
http://purl.obolibrary.org/obo/UBERON_0007106

## Suggested parent term

chorion membrane
(material anatomical entity higher up in the hierarchy)

## Use case

It should be used to indicate a specific organ part when describing from which part of the human body samples/cells were obtained for experiments.

## Attribution

N/A

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
I'll be helping with HCAO requests. I will work with @zoependlington and @dosumis to ensure that this term is added to the next release of HCAO. Thanks,
Paola

**Comment by ami-day** [comment]
Hi @paolaroncaglia 
Thanks for this. When will the next release of HCAO likely be? or has the above requested term already been added?

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
Sorry for the delay. I'm meeting my colleagues tomorrow to discuss the HCAO pipeline (including this ticket), so if a new release isn't done tomorrow, I will at least be able to give you a date. 
Thanks,
Paola

**Comment by ami-day** [comment]
Hi @paolaroncaglia Thanks sounds good. I think there are a couple of other new terms @rays22 was thinking of requesting, and maybe also @ESapenaVentura or @mshadbolt... Just thought I'd mention here in case it's easier to communicate about adding new terms in the new release in 1 place

**Comment by paolaroncaglia** [comment]
@ami-day 
A new HCAO release is tentatively planned for Thursday Dec 3rd. If you or any of your colleagues would like to request terms that already exist in Uberon or CL to be imported into HCAO, please open new tickets in the HCAO tracker by Wednesday Dec 2nd, and I'll address them. (Terms that don't exist in Uberon or CL and need creating de novo may also be requested, but they wouldn't be available in time for the next HCAO release.)
Feel free to ask if you have any questions. Thanks,
Paola

**Comment by ami-day** [comment]
Hi @paolaroncaglia thanks for this info. Is the HCAO release still going ahead today? it would be good to confirm when I can add the new term to my metadata and upload it for validation.

**Comment by paolaroncaglia** [comment]
@ami-day 
The term UBERON_0007106 chorionic villus is now in the HCAO release, and will be in public OLS in a day or so. Thanks.
