### ISSUE TITLE
new term request - transition zone of prostate

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#65]
For new term requests, please provide the following information:

## Preferred term label
transition zone of prostate

(e.g., Asplenia)

## Synonyms
prostate transition zone
transition zone of human prostate

(e.g., Absent spleen)

## Textual definition

The region of the prostate gland anterior to the central and peripheral zones, surrounding the proximal urethra. It is the zone of the prostate gland that grows the most throughout life, and is responsible for benign prostatic hypertrophy.

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)
http://purl.obolibrary.org/obo/UBERON_0002367

## Use case

Please specify under what circumstances you anticipate this term being used in the HCA metadata.
Will be used for 'organ part' fields in HCA metadata spreadsheets.

## Attribution
https://orcid.org/0000-0002-7431-4139

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@rachadele 
cc @dosumis 
I started a [discussion in the Uberon tracker](https://github.com/obophenotype/uberon/issues/1670) to figure out if this request (and 2 more from Rachel) are in scope for Uberon. If not, I'll add the terms in EFO. Thanks.

**Comment by rachadele** [comment]
amazing, thank you!

**Comment by paolaroncaglia** [comment]
@rachadele 
FYI I'm closing this ticket (and #66 and #67 ) as duplicates of https://github.com/obophenotype/uberon/issues/1670.
