### ISSUE TITLE
new term request - peripheral zone of prostate

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#66]
For new term requests, please provide the following information:

## Preferred term label
peripheral zone of prostate

(e.g., Asplenia)

## Synonyms
prostate peripheral zone
peripheral zone of human prostate

(e.g., Absent spleen)

## Textual definition

The region of the prostate that is located posterior to central and transition zones, surrounding the distal urethra. It is the zone of origin for the vast majority of prostatic cancer.

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

http://purl.obolibrary.org/obo/UBERON_0002367

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

## Use case

Will be used for 'organ part' fields in HCA metadata spreadsheets

Please specify under what circumstances you anticipate this term being used in the HCA metadata.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id
0000-0002-7431-4139

**Comment by paolaroncaglia** [comment]
See https://github.com/obophenotype/uberon/issues/1670
