### ISSUE TITLE
new term request - central zone of prostate

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#67]
For new term requests, please provide the following information:

## Preferred term label

central zone of prostate

(e.g., Asplenia)

## Synonyms

prostate central zone
central zone of human prostate

(e.g., Absent spleen)

## Textual definition

This region of the prostate gland that is located between the peripheral and transition zones, surrounding the ejaculatory ducts. It gives rise to a very small percentage of prostate cancers, though these cancers are frequently more aggressive, often resulting in invasion of the seminal vesicles.

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term
http://purl.obolibrary.org/obo/UBERON_0002367

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

## Use case

Will be used in 'organ part' fields in HCA metadata spreadsheets.

Please specify under what circumstances you anticipate this term being used in the HCA metadata.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id
0000-0002-7431-4139

**Comment by paolaroncaglia** [comment]
See https://github.com/obophenotype/uberon/issues/1670
