### ISSUE TITLE
new term request - head and neck lymph node

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#68]
For new term requests, please provide the following information:

## Preferred term label

head and neck lymph node

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

lymph node of the head and neck

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hcao)

http://purl.obolibrary.org/obo/UBERON_0000029

## Use case

Please specify under what circumstances you anticipate this term being used in the HCA metadata.

Will be used in 'organ part' field of HCA metadata spreadsheet.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@rachadele 
The term you need was created very recently in Uberon, but won't be available in OLS (or for the HCA pipeline) until the next Uberon release. The term is UBERON:0038849 'craniocervical lymph node' (note for self: https://github.com/obophenotype/uberon/commit/a3b41da7dacd642c2d616652b8912a1175a37009). 
Action items for me:
- [ ] Enquire re date of next Uberon release
- [ ] Then include term in HCAO

**Comment by rachadele** [comment]
thanks!

**Comment by paolaroncaglia** [comment]
@rachadele 
The term UBERON:0038849 'craniocervical lymph node' is now in HCAO (not in public OLS yet, as HCAO was just released).
I'll close this ticket. Thanks,
Paola
