### ISSUE TITLE
new term request - cytokine secretion assay

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#69]
For new term requests, please provide the following information:

## Preferred term label

cytokine secretion assay

## Synonyms

pan-cytokeratin staining

## Textual definition

Assay measuring the types and amounts of cytokines that are released as the consequence of a signaling event. Cytokines can be quantitated using ELISA-based kits, PCR array, etc.

## Suggested parent term

Cue signal response assay
http://www.bioassayontology.org/bao#BAO_0000042

## Use case

will be used as 'enrichment protocol' for HCA metadata spreadsheets

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,

This will be an EFO term, so I opened a ticket in the EFO tracker and assigned it to myself: https://github.com/EBISPOT/efo/issues/893

Closing this one now. Thanks,

Paola
