### ISSUE TITLE
Adding imaging fluorophores to HCAO

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ontology#7]
It would be preferable for the field imaging_protocol.target.fluorophore to support an ontology entry. To do this we would need to add some terms to HCAO either from CHEBI or FBbi.

Examples herein would be an excellent start:
http://purl.obolibrary.org/obo/FBbi_00000455

Alternatively we could look at CHEBI entities with `has role some fluorochrome`.

**Comment by daniwelter** [comment]
I don't think Chebi would be particularly well suited for this as it would come with a great big unnecessary import chain. I have added the relevant FBBI terms to our FBBI slim and this should be available in our internal OLS instance before too long

**Comment by zperova** [comment]
Here is an example list of possible fluorophores we might encounter is imaging datasets: https://www.chroma.com/products/fluorochrome

**Comment by hewgreen** [comment]
Is this done to your satisfaction @zperova ?

**Comment by daniwelter** [comment]
Closing this ticket as there has been no movement on it in months. Please file a new ticket if this is still an issue.
