### ISSUE TITLE
Add new cell type term

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#72]
For new term requests, please provide the following information:

## Preferred term label

fetal hepatobiliary hybrid progenitor cell

## Textual definition

Here, we report the transcriptional signature of distinct hepatic cell types in fetal and adult human liver, including a fetal hepatobiliary hybrid progenitor (HHyP) population. Exclusively within the CD235a−/CD45−/EpCAM+/NCAM+ population of human fetal liver we identify a cluster of cells that closely resembles EpCAM+ biliary cells identified in adult liver, expressing both biliary and hepatic markers which we label here as HHyP cells.

** taken from the [paper](https://www.nature.com/articles/s41467-019-11266-x#Abs1)

## Suggested parent term

Not sure

## Use case

This is a cell type for one of the GEO datasets (GSE130473) we are wrangling.

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

I "moved" this request to the Cell Ontology tracker, https://github.com/obophenotype/cell-ontology/issues/840
So I'll close this HCAO ticket now. Thanks.
