### ISSUE TITLE
Help mapping cell types to correct CL ontologies

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#73]
We are wrangling [GSE89322](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE89322) and need to map their cell types to CL ontologies. Could you please help us map to the correct ontology? 

**classic dendritic cell (cDCs)**
- is conventional dendritic cell (CL:0000990) appropriate to use here?

**precursor dendritic cell (pre-DCs)**
- is pre-conventional dendritic cell (CL:0002010) appropriate to use here?

**Here is a description from their paper**(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6599345/):
For sorting pre-cDCs, enriched cells were stained for CD14 (TuK4, Qdot-655, Invitrogen), CD3 (OKT3, Brilliant Violet (BV) 650, Biolegend), CD19 (HIB19, BV650, Biolegend), CD56 (HCD56, BV650, Biolegend), CD66b (G10F5, PerCP-Cy5.5, Biolegend), CD303 (201A, PerCP-Cy5.5, Biolegend), CD1c (L161, APC-Cy7, Biolegend), CD141 (M80, PE-Cy7, Biolegend), CD34 (581, AlexaFluor700, Biolegend), CD117 (104D2, BV421, Biolegend), CD135 (4G8, PE, BD), CD45RA (HI100, BV510, Biolegend), CD116 (4H1, FITC, Biolegend) and CD115 (9-4D2-1E4, APC, Biolegend) for 40 min on ice. Pre-cDCs were isolated as Lin(CD3/19/56/14)- Granulocyte(CD66b)-pDC(CD303)-cDC(CD1c/CD141)-CD34-CD117 + CD135 + SSC lo CD116 + CD115-CD45RA+ cells. cDC1 were isolated as Lin(CD3/19/56/14)- Granulocyte(CD66b)-pDC(CD303)-CD141+ cells. cDC2 were isolated as Lin(CD3/19/56/14)- Granulocyte(CD66b)-pDC(CD303)-CD1c + cells.

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

conventional dendritic cell (CL:0000990) is defined as “Conventional dendritic cell is a dendritic cell that is CD11c-high.”. Does this fit with the paper?
Also from this other paper PMID: 23516985, if it helps: 
“Classical Dendritic Cells
cDCs refer to all DCs other than pDCs [Plasmacytoid Dendritic Cells]. cDCs form a small subset of tissue hematopoietic cells that populate most lymphoid and nonlymphoid tissues.”

If conventional dendritic cell (CL:0000990) is appropriate to use, then pre-conventional dendritic cell (CL:0002010) would be appropriate to represent precursor dendritic cell (pre-DCs).

You may also consider the human-specific CL:0001056 'dendritic cell, human' (definition "A dendritic cell with the phenotype HLA-DRA-positive.”, rdfs:comment "This cell type is compatible with the HIPC Lyoplate markers for 'dendritic cell'. The inclusion of HLA-DRA in the definition restricts this definition to human dendritic cells.”)

Let me know if you have any concern and I might consult with one of the CL experts.

**Comment by pnejad** [comment]
@paolaroncaglia  Thank you for your feedback! I think I will use conventional dendritic for this dataset. The paper refers to conventional and classical dendritic cells as cDC's, which makes me believe they are the same.

**Comment by paolaroncaglia** [comment]
@pnejad 
Thanks. I'll close this ticket then.
