### ISSUE TITLE
Add 'peripheral blood' to uberon

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#74]
## Preferred term label

peripheral blood

## Textual definition

Peripheral blood is the fluid that travels through your heart, arteries, capillaries, and veins. Its most important function is to transport oxygen and other nutrients to your body’s cells and tissues and to remove carbon dioxide and other waste products from the body. 

Definition copied from this [site](https://sterlingpath.com/hematology/peripheral-blood-and-blood-smear-procedure/#:~:text=Peripheral%20blood%20is%20the%20fluid,waste%20products%20from%20the%20body.).

## Suggested parent term

UBERON:0000178

## Use case

This is the organ_part for a specimen that is part of a GEO dataset (GSE89322) we are wrangling.

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

Based on this bit from the paper associated to GSE89322 (PMID: 31253076, start of Methods section)
"Human peripheral blood samples were purchased from New York Blood Center (New York) and processed 24-48 h post-collection. Fresh mononuclear cells were isolated from cord blood or peripheral blood by density centrifugation..."
I believe that the most appropriate terms for you to use would be the existing 
CL:2000001 'peripheral blood mononuclear cell'
and
CL:2000095 'cord blood hematopoietic stem cell'.
These are more specific and informative than 'peripheral blood', but if an anatomical term is required, I could make the case with Uberon to create 'peripheral blood' and differentiate it from its parent 'blood' by specifying that "Peripheral blood cells are the cellular components of blood, consisting of red blood cells (erythrocytes), white blood cells (leucocytes), and platelets, which are found within the circulating pool of blood and not sequestered within the lymphatic system, spleen, liver, or bone marrow." (see https://en.wikipedia.org/wiki/Peripheral_blood_cell). Let me know your preference.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@pnejad 
I'll close this ticket, but if you have any concern, please feel free to comment/reopen. Thanks.
