### ISSUE TITLE
lumbar puncture (collection protocol)

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#75]
## Preferred term label

lumbar puncture

## Synonyms

spinal tap

## Textual definition

A method to collect cerebrospinal fluid (CSF) from a human donor, using a needle.

## Suggested parent term

collecting specimen from organism (http://purl.obolibrary.org/obo/OBI_0600005)

## Use case

human cell atlas collection protocol method

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] xref NCIT:C15327 Lumbar Puncture

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
I moved this to an EFO ticket, so I'll close this issue as a duplicate. I have tagged you in the EFO ticket, so you'll receive a notification when the term is available. Thanks.
Paola
