### ISSUE TITLE
new term request - barcoded plate-based single cell RNA-seq

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#76]
## Preferred term label

barcoded plate-based single cell RNA-seq

## Textual definition

A single-cell RNA sequencing library construction method that generates barcodes libraries and is plate-based. An example would be a plate-based method that is not Smart-seq2 or a modified, barcoded version of Smart-seq2.

## Suggested parent term

single-cell library construction
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010183&viewMode=All&siblings=false

## Use case

To be used in HCA metadata to indicate a single-cell library construction method.

**Comment by ami-day** [comment]
Hi @paolaroncaglia we would like to request a new library construction method ontology term. Is this still the correct place to enter our HCA ontology requests? Many thanks!

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
This particular term is in scope for EFO, so I'll make a ticket there. 
For requests for new cell type or anatomy terms, @mshadbolt drafted a decision-tree document but I don't have the link handy, sorry.
In general though, I think that @zoependlington was planning to investigate if we should move all HCA ontology requests to another tracker. I'm not sure if she has any update. For now, I'd say it's ok to enter them here so they're all in one place. Thanks.

**Comment by paolaroncaglia** [comment]
Note for self: this term request was moved to https://github.com/EBISPOT/efo/issues/958, so this HCAO ticket may be closed when the points in my previous comment are addressed.
