### ISSUE TITLE
[ENQ] Import Data Use Ontology DUO into HCAO

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#77]
Hi both

We would like to start using the DUO ontology to show how data in the HCA DCP can be used or what limitations/restrictions exist on its use. Therefore we would need to add DUO to the HCAO. Is this something that is possible?

Let me know if there is any more information you would need from us to start work on this.

Thanks in advance! 

This relates to an update we want to make to our project schema: https://github.com/HumanCellAtlas/metadata-schema/issues/1342

**Comment by paolaroncaglia** [comment]
@mshadbolt 
I presume that importing DUO into HCAO should be possible and hopefully relatively straightforward (see https://github.com/HumanCellAtlas/ontology/blob/master/src/ontology/get_mirrors.sh), but I'll need help from @zoependlington to implement. (DUO contains less than 300 terms, so I assume we'll import it all rather than a slim.) I'll contact her offline.

**Comment by mshadbolt** [comment]
ok great, thanks!

**Comment by paolaroncaglia** [comment]
@mshadbolt 
We'll try to implement the DUO import in time for the next HCAO release if possible (March 18th). Thanks.

**Comment by mshadbolt** [comment]
That would be great thanks!

**Comment by mshadbolt** [comment]
Hi @paolaroncaglia I just wanted to check in on this and whether it will be in the release this week as we are preparing to add a change to our schema that will rely on being able to use these so wanted to make sure of that before we make the change. Thanks!

**Comment by zoependlington** [comment]
@mshadbolt The DUO import will be in HCAO for the 18th March release.

**Comment by paolaroncaglia** [comment]
@zoependlington 

> The DUO import will be in HCAO for the 18th March release.

Thanks! I'll close this ticket.
