### ISSUE TITLE
[ITR] Microscopy ontology branch

### ISSUE THREAD

**Issue by paolaroncaglia** [HumanCellAtlas/ontology#81]
This is a placeholder, following a Slack conversation with Laura Clarke:
"when we start capturing imaging data we are going to need microscopy ontologies, if the current microscopy ontologies specified by the schema are still the right ones to use is a different question". 
I believe that the current schema is pointing to FBbi:00000241 'microscopy', which isn't in HCAO at the moment.
- [ ] Evaluate if there's a need for HCA to import FBbi:00000241 'microscopy' into HCAO, or evaluate alternative options.

**Comment by paolaroncaglia** [comment]
Hi @pnejad and @dosumis ,
I'm reviewing tickets in this tracker. Just a reminder about this one; please feel free to add the topic to one of our monthly meetings' agenda if/when appropriate. Thanks.
Paola

**Comment by pnejad** [comment]
@paolaroncaglia  thank you for bringing this to my attention! I will talk to the wranglers to get a better understanding of ontology needs for imaging assays.

**Comment by dosumis** [comment]
Note that specific assays (e.g. Merfish) are/should-be in EFO.

**Comment by paolaroncaglia** [comment]
> Note that specific assays (e.g. Merfish) are/should-be in EFO.

FYI, to expand on some of the concepts that @dosumis mentioned, EFO already has e.g.
EFO:0008992 MERFISH 
EFO:0010961 'Visium Spatial Gene Expression'
Both are also in the EFO HCA subset.

**Comment by pnejad** [comment]
@paolaroncaglia I checked in with the wranglers and this tickets can be closed. If we need any ontologies related to microscopy in the future we can create a new ticket.

**Comment by paolaroncaglia** [comment]
@pnejad thank you for your feedback! Closing now.
