### ISSUE TITLE
[NTR] Please add sci-CAR ATAC-seq and sci-CAR RNA-seq to EFO/HCAO

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#82]
## Preferred term label

sci-CAR ATAC-seq & sci-CAR RNA-seq

## Textual definition

Description from the [paper](https://science.sciencemag.org/content/361/6409/1380):

Single-cell combinatorial indexing (sci) methods use split-pool barcoding to uniquely label the nucleic acid contents of single cells or nuclei (7–13). Here we describe sci-CAR, which jointly profiles single-cell chromatin accessibility and mRNA (CAR) in a scalable fashion. sci-CAR effectively combines sci–ATAC sequencing (sci-ATAC-seq) and sci-RNA-seq into a single protocol (Fig. 1) by the following steps: (i) Nuclei are extracted, with or without fixation, and distributed to wells. (ii) A first RNA-seq “index” is introduced by in situ reverse transcription (RT) with a polythymidine [poly(T)] primer that bears a well-specific barcode and a unique molecular identifier (UMI). (iii) A first ATAC-seq index is introduced by in situ tagmentation with Tn5 transposase that bears a well-specific barcode. (iv) All nuclei are pooled and redistributed by fluorescence-activated cell sorting to multiple plates. (v) After second-strand synthesis of cDNA, nuclei in each well are lysed, and the lysate is split into RNA- and ATAC-dedicated portions. (vi) To provide a second priming site for amplification of 3′ cDNA tags, the RNA-dedicated lysate is subjected to transposition with unindexed Tn5 transposase. 3′ cDNA tags are amplified with primers corresponding to the Tn5 adaptor and RT primer. These primers also bear a well-specific barcode that is the second RNA-seq index. (vii) The ATAC-seq–dedicated lysate is amplified with primers specific to the barcoded Tn5 adaptors from (iii). These primers also bear a well-specific barcode that is the second ATAC-seq index. (viii) Amplicons from RNA-seq– and ATAC-seq–dedicated lysates are respectively pooled and sequenced. Each sequence read is associated with two barcodes that correspond to each round of indexing. As with other sci protocols, most nuclei pass through a unique combination of wells, thereby receiving a unique combination of barcodes that can be used to group reads derived from the same cell. Because the barcodes introduced to RNA-seq and ATAC-seq libraries correspond to specific wells, we can link the mRNA and chromatin accessibility profiles of individual cells.

## Suggested parent term

single cell library construction EFO:0010183

## Use case

Library construction methods used in one of the datasets we are wrangling: [GSE117089](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117089)

**Comment by paolaroncaglia** [comment]
Thanks @pnejad .
I moved this request to an EFO ticket (https://github.com/EBISPOT/efo/issues/1079), so I'll close this as duplicate.
Best,
Paola
