### ISSUE TITLE
[NTR] Microwell-Seq

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#83]
## Preferred term label

Microwell-Seq

## Synonyms

Microwell-seq
microwell-seq

## Textual definition

Microwell-Seq is a convenient, low-cost, and robust platform for High-Throughput single-cell RNA-Sequencing.

Microwell-Seq workflow: an agarose plate with microwells is used to trap 5-10K individual cells. Barcoded magnetic beads are loaded and trapped into each well. Each single bead is conjugated with 107–108 oligonucleotides, which share the same cellular barcode. Each oligonucleotide consists of a primer sequence, a cell barcode, a unique molecular identifier (UMI), and a poly T tail. After incubation of beads and cells in a soft flow of lysis buffer, beads with captured mRNA are retrieved with a magnet. Beads are collected in a tube in which reverse transcription and template switch steps are performed using the Smart-seq2 protocol (Picelli et al., 2013). Amplified cDNA is fragmented by a customized transposase that carries two identical insertion sequences. The 3′ ends of the transcripts are then enriched during library generation using PCR and sequenced using an Illumina Sequencing Platform.

Method Publication Reference: https://www.sciencedirect.com/science/article/pii/S0092867418301168

## Suggested parent term

single cell library construction
http://www.ebi.ac.uk/efo/EFO_0010183

## Use case

HCA metadata single cell RNA sequencing library construction method

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
I opened an EFO ticket for this term request, and I tagged you there (https://github.com/EBISPOT/efo/issues/1083), so I'll close this HCAO ticket as duplicate. The EFO term will be created in time for the next EFO release (May 17th), and will be imported in HCAO shortly after (the next HCAO released is currently planned for ~ May 20th).
Thanks,
Paola
