### ISSUE TITLE
[ITR]  Please add UBERON:0018105 to HCAO

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#87]
## Source ontology identifier

UBERON:0018105

## Destination ontology

HCAO

## Preferred term label

perifoveal part of retina

## Synonyms

perifovea

## Textual definition

The outermost region surrounding the fovea centralis

## Suggested parent term

fovea centralis (UBERON:0001786)? 

## Use case

Organ_part for a specimen in one of our datasets

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

I added UBERON:0018105 'perifoveal part of retina' to the list of terms to be imported at the next HCAO release, scheduled for July 19th. I'll update this ticket when that's done.

Thanks,
Paola

**Comment by pnejad** [comment]
Thank you, @paolaroncaglia!

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,
UBERON:0018105 'perifoveal part of retina' has been manually imported into the new HCAO release (see https://github.com/ebi-ait/hca-ebi-dev-team/issues/438). I'll close this ticket. Any issue, please let us know. 
Thanks,
Paola
