### ISSUE TITLE
[NTR] Nx1-seq 

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#89]
## Preferred term label

Nx1-seq

## Textual definition

Next generation one-cell sequencing (Nx1-seq)  is a single cell transcriptomic library preparation method which conjugates polystyrene beads to barcode nucleotides by means of emulsion PCR using oligo-dTs. The beads are mixed on a chamber slide containing PDMS microwells which fit one cell per well. The slide is then washed with a cell suspension to capture and barcode individual cells.

PMID: 30968360

## Suggested parent term

EFO:0010183
single cell library construction

## Use case

 library preparation protocol ontology

## Attribution

https://orcid.org/0000-0002-7431-4139

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
The new term is EFO_0030021 (Nx1-seq).
It will be public with the next EFO release (Aug. 16th).
The HCAO release is then scheduled for Aug. 18th. It will import the new EFO term. Zoë (@zoependlington ) will take care of both the EFO and the HCAO releases. She will then ask the EBI HCA developers to deploy the HCAO release in the HCA OLS instance; I asked Zoë to tag you so you can follow when that's done - the term will then be available to you.
FYI, I'll be on leave as of now and until August 24th. Feel free to assign requests to me in the meantime, and I'll pick them up on my return.
Paola
