### ISSUE TITLE
[ENQ] Terms for “treatment”, “donor”, “replicate” and “batch”

### ISSUE THREAD

**Issue by paolaroncaglia** [HumanCellAtlas/ontology#91]
cc @pnejad

HCA wranglers asked for our opinion on what ontology terms would fit best to represent “treatment”, “donor”, “replicate” and “batch”. The metadata they need to describe is the content of GSE173560_metaData_HR_MtbAggs.txt.gz from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE173560?, where a summary and overall design are also available. They were initially looking into using EDAM. However, I think that the following may fit better:

treatment: 
EFO:0000727 ‘treatment’ (“A planned process intended to modify or alter a condition or characteristic of an organism or individual.”);
it’s not in HCAO yet;
it’s in the experimental process branch, which is in HCAO, so we could simply import it into HCAO.

donor:
EFO:0009635 ‘blood donor’ (“Someone from whom blood is removed for transfusion or other purpose. [ NCI ]”)
(I assume it’s blood that’s being donated, otherwise you may consider EFO:0009633 ‘tissue donor’ or EFO:0009634 ‘organ donor’);
it’s not in HCAO yet;
it’s a child of BFO:0000023 ‘role’ which is already in HCAO, so we could simply import it into HCAO.

replicate:
EFO:0002090 ‘technical replicate’ (“A technical replicate is a replicate role where the same BioSample is use e.g. the same pool of RNA used to assess technical (as opposed to biological) variation within an experiment.”)
(I assume it’s technical replicates rather than biological ones, based on the text “3 repeats for each of 4 infection conditions from 5 donors”, otherwise you may use the broader EFO:0000683 ‘replicate’);
it’s not in HCAO yet;
it’s a child of BFO:0000023 ‘role’ which is already in HCAO, so we could simply import it into HCAO.

batch:
EFO:0005067 ‘block’ (exact synonym “batch”; “A block or batch is an experimental unit arrangement into a group which is similar to one another. Typically, a blocking factor is a source of variability that is not of primary interest to the experimenter. An example of a blocking factor might be the sex of a patient; by blocking on sex, this source of variability is controlled for, thus leading to greater accuracy.”);
it’s not in HCAO yet;
it’s in the experimental process branch, which is in HCAO, so hopefully we could simply import it into HCAO.

@pnejad
If you could please confirm that the terms above are appropriate, I’ll look into making them available to HCA.
Thanks,
Paola

**Comment by pnejad** [comment]
Hi @paolaroncaglia, we need to fill out the "analysis_file.file_core.content_description.ontology" field, which requires the ontology to come from EDAM.

So within EDAM, is there a general ontology that could be used to describe a metadata file with descriptions of treatment, batch, etc.?

**Comment by paolaroncaglia** [comment]
Hi @pnejad,
Thanks for clarifying. Then I think you may want to look in the 'Data' -> 'Report' branch of EDAM. Here are a few options, from broader to more specific:

data:2048 'Report' ("A human-readable collection of information including annotation on a biological entity or phenomena, computer-generated reports of analysis of primary data (e.g. sequence or structural), and metadata (data about primary data) or any other free (essentially unformatted) text, as distinct from the primary data itself.")

data:2337 'Resource metadata' (synonym "provenance metadata") ("Data concerning or describing some core computational resource, as distinct from primary data. This includes metadata on the origin, source, history, ownership or location of some thing.") 
BUT has a comment "This is a broad data type and is used a placeholder for other, more specific types."

data:3113 'Sample annotation' ("Annotation on a biological sample, for example experimental factors and their values.")

'Sample annotation' is a child of 'Resource _metadata_', so this one could fit well?

**Comment by rachadele** [comment]
@paolaroncaglia We think "sample annotation" would be the best fit!

**Comment by paolaroncaglia** [comment]
> @paolaroncaglia We think "sample annotation" would be the best fit!

@rachadele @pnejad 
Thanks for confirming. The term is already in HCAO, so I'll close this ticket. Have a good day!
Paola
