### ISSUE TITLE
[ITR] Liver fibrosis

### ISSUE THREAD

**Issue by idazucchi** [HumanCellAtlas/ontology#96]
## Source ontology identifier
HP:0001395

## Destination ontology
HCAO

## Preferred term label
Hepatic fibrosis

## Synonyms
Liver fibrosis

## Textual definition
The presence of excessive fibrous connective tissue in the liver. Fibrosis is a reparative or reactive process.

## Suggested parent term
liver disease
MONDO:0005154

## Use case
Used for known disease in the donor organism schema

## Attribution
https://orcid.org/0000-0002-4900-7575

**Comment by paolaroncaglia** [comment]
Dear @idazucchi ,

Nice to e-meet you. @dosumis and I looked into your request, and unfortunately the specifications for disease terms in HCAO don't allow for HP terms (as per https://data.humancellatlas.org/metadata/dictionary/biomaterial/donor_organism/#diseases). We can't really import an HP term in the Mondo hierarchy in HCAO. The options are:

Use the broader term 'liver disease', or see if any existing child of 'liver disease' could be used based on the details of the dataset you're wrangling; 

Request a new term in Mondo called 'hepatic fibrosis (disease)' (to distinguish it from the HP phenotype term). This would require waiting for Mondo to create the term and release it (they release monthly), then wait for the first available HCAO monthly release to bring the term in. I can help with the term request if you choose this option. 

Best wishes,

Paola

**Comment by paolaroncaglia** [comment]
P.S. I scanned the paper and I think you do need 'hepatic fibrosis (disease)' or 'fibrotic liver disease' after all if you want a specific disease term, though the broader 'liver disease' wouldn't be incorrect. My understanding is that hepatic fibrosis is a hallmark of more than one type of liver disease, but I'm not an expert in that field.

**Comment by idazucchi** [comment]
Dear @paolaroncaglia, 
Nice to e-meet you too!
Thanks for looking at this. I discussed it with @ESapenaVentura and I’d like to follow the second option you suggested, requesting a new term in Mondo called 'hepatic fibrosis (disease)’.
How can I move forward?

**Comment by paolaroncaglia** [comment]
Dear @idazucchi ,
I requested the term to Mondo and tagged you there (https://github.com/monarch-initiative/mondo/issues/4000).
Let's see what they say. I'll leave this ticket open.
Best,
Paola

**Comment by paolaroncaglia** [comment]
Dear @idazucchi ,
Mondo editors will aim to add the new term you need in time for the December Mondo release. I'm not sure when exactly that will be, but it's usually around the first week of the month. I'll update this ticket when that's done. Hopefully you'll have it in time for the mid-December HCAO release.

**Comment by paolaroncaglia** [comment]
Dear @idazucchi ,
Mondo added the new term you requested as MONDO:0100427 'fibrotic liver disease'.
The term will be available to you after the next Mondo release and the following HCAO release, so if all goes well, after Dec 16th.

**Comment by idazucchi** [comment]
Dear @paolaroncaglia,
This is wonderful news! Thank you for the update.

**Comment by paolaroncaglia** [comment]
Dear @idazucchi ,
FYI, the Mondo term you need, 'fibrotic liver disease', is now publicly available in Mondo but with a different ID than previously noted. The term is [MONDO:0100430 fibrotic liver disease](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100430).
It should be available to you in the HCA ontology a couple of days after the next HCAO release (scheduled for Dec 16th).
