### ISSUE TITLE
Ontology term request for bulk ATAC-Seq

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#98]
## Preferred term label

ATAC-seq

## Textual definition

ATAC-seq (Assay for Transposase-Accessible Chromatin using sequencing) is a technique used in molecular biology to assess genome-wide chromatin accessibility. The ATAC-Seq method relies on next-generation sequencing (NGS) library construction using the hyperactive transposase Tn5. 

## Suggested parent term

library preparation
http://purl.obolibrary.org/obo/OBI_0000711

## Use case

library construction method ontology term (library preparation protocol schema)

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
Commenting briefly as I'm in the middle of something else, but it looks like the existing term [EFO:0007045 ATAC-seq](http://www.ebi.ac.uk/efo/EFO_0007045) would fit your need? It's a child of DNA-seq, and descendant of assay by molecule and assay by sequencer.

**Comment by paolaroncaglia** [comment]
@ami-day 
It's also in the EFO HCA subset, see [here](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007045).

**Comment by ami-day** [comment]
Hi @paolaroncaglia yes exactly, the existing term is not working for me because the parent is not 'library preparation'. Would it be possible to add it?

**Comment by paolaroncaglia** [comment]
Hi @ami-day ,
ATAC-seq is now (also) a child of 'library preparation'. The change will be in the EFO release scheduled for Feb 15th, and will then be imported in the HCAO release the following day.
