### ISSUE TITLE
'cell type' is positioned incorrectly in HCAO due to CLO import

### ISSUE THREAD

**Issue by paolaroncaglia** [HumanCellAtlas/ontology#99]
I'm opening this ticket as a reminder that 'cell type' is positioned incorrectly in HCAO due to the CLO (Cell Line Ontology) import.
Details in [ticket that @zoependlington opened with CLO](https://github.com/CLO-ontology/CLO/issues/65). 
If CLO fixes and runs a new CLO release, the fix will be imported automatically when running the HCAO pipeline, and we can then check that everything looks good.
If CLO does not envision having resources to fix and release, we'll reassess (this issue was noticed by me randomly and doesn't seem to be breaking anything for HCAO).

UPDATE (7/3/22): in a [separate CLO ticket](https://github.com/CLO-ontology/CLO/issues/66#issuecomment-1049417980), Oliver recently wrote that "the CLO is still actively maintained. It is not actively developed due to our busy schedule in the last couple of years of the COVID-19 pandemic". Perhaps we could tag him directly in "our" CLO ticket and ask for advice.

UPDATE (15/3/22): I followed up with Oliver on the CLO ticket; we can assess when he replies.

**Comment by yongqunh** [comment]
This should be solved now with the updated CLO. Please check out. Thanks!

**Comment by paolaroncaglia** [comment]
@yongqunh 

> This should be solved now with the updated CLO. Please check out. Thanks!

Thank you!
